project:
  type: website
  resources: 
    - "images/rscreencasts_social_preview.png"
  render:
    - "index.qmd"
    - "about.qmd"
    - "resources.qmd"
    - "content_pages/*.qmd"

website:
  title: "R Screencasts"
  site-url: "https://www.rscreencasts.com"
  favicon: /images/favicon-32x32.png
  twitter-card:
    title: "R Screencasts"
    image: "/images/rscreencasts_social_preview.png"
    site-url: "https://www.rscreencasts.com"
    card-style: summary_large_image
    description: "Awesome data analysis screencasts from a top Data Scientist"
  open-graph:
    title: "R Screencasts"
    image: "/images/rscreencasts_social_preview.png"
    description: "Awesome data analysis screencasts from a top Data Scientist"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: resources.qmd
        text: Resources
      - href: about.qmd
        text: About
  page-footer: 
    center: |
      Vids by [David Robinson](https://twitter.com/drob). 
      Timestamps & rich content by [Alex Cookson](https://twitter.com/alexcookson) and [Eric Fletcher](https://twitter.com/iamericfletcher).
      Website by [Oscar Baruffa](https://twitter.com/OscarBaruffa), sign up to my [newsletter](https://oscarbaruffa.com/newsletter/) for R, data and careers
      

format:
  html:
    include-in-header: 
      - plausible-analytics.html
     
    theme: flatly
    css: styles.css
    toc: true



