---
title: "Australian Animal Outcomes"
description: "Data manipulation, Web Scraping (rvest package) and SelectorGadget, Animated Choropleth Map"
date: 2020-07-21
date-format: long
---

Notable topics: Data manipulation, Web Scraping (rvest package) and SelectorGadget, Animated Choropleth Map

Recorded on: 2020-07-21

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/australian-animal-outcomes.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:1:20

Using `use_tidytemplate` to open the project dataset with the package's tidytemplate Rmd

use_tidytemplate

tidytuesdayR



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=80" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:4:30

Using `rename` to rename `Total` column to `total`

rename

dplyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=270" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:6:20

Using `fct_reorder` to reorder stacked barplot with `weight = sum`

fct_reorder

forcats



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=380" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:00

Using `fct_lump` with `w = n` to lump together `outcome` factor levels displaying the most frequenct with rest lumped into `other`

fct_lump

forcats



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=420" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:15

Using `fct_recode` to combine the factor level `In Stock` with `Currently In Care`

fct_recode

forcats



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=555" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:10

Using `fct_reorder` to reorder `facet_wrap` panels

fct_reorder

forcats



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=730" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:03

Using `scale_y_continuous` with `labels = comma` to separate digits with comma

scale_y_continuous

ggplot2 | scales



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=783" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:10

Using `complete` to complete account for missing combinations of data where the value is 0 in the `released` column

complete

tidyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:10

Using `max (year)` within `filter` to subset the data displaying only the most recent year

max

base



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:30

Using `pivot_longer` to pivot location variables from wide to long

pivot_longer

tidyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:45

Web Scaraping table from Wikipedia with `SelectorGadget` and `Rvest`

read_html | html_nodes | map |

rvest | janitor



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1305" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:45

Using `str_to_upper` to upper case the values in the `shorthand` column

str_to_upper

stringr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1545" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:13

Using `parse_number` to remove commas from `population` and `area` columns

parse_number

readr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1633" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:55

Using `bind_rows` to bind the two web scraped tables from Wikipedia together by row and column

bind_rows

dplyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1735" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:35

Using `inner_join` to combine the Wikipedia table with the original data set

inner_join

dplyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1775" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:47

Using `mutate` to create new `per_capita_million` column to show `outcome` on a per million people basis

mutate

dplyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=1787" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:25

Using `summarize` to create new column `pct_euthanized` showing percent of cats and dogs euthanized over time. Formula accounts for 0 values thus avoiding a resulting empty vector.

summarize

dplyr



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=2245" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:10

Using `scale_y_continuous` with `labels = percent` to add percentage sign to y-axis values

scale_y_continuous

ggplot2 | scales



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=2350" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:45

Create a choropleth map of Australia using an Australian States `Shapefile` using the `sf` and `ggplot2` packages | Troubleshooting begins at 44:25 (downsizing / downsampling with `sf_simplify`)

read_sf | geom_sf | sf_simplify

sf | ggplot2



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=2565" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:55:45

Add animation to the map of Australia showing the percent of cats euthanized by region using `gganimate`

transition_manual

gganimate



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=3345" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:01:35

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/E2amEz_upzU?start=3695" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

