---
title: |
  Beyonce and Taylor Swift Lyrics
description: |
  Text analysis, `tf_idf`, Log odds ratio, Diverging bar graph, Lollipop graph
date: 2020-09-28
date-format: long
aliases:
  - "Beyonce and Taylor Swift Lyrics.html"
---

Notable topics: Text analysis, `tf_idf`, Log odds ratio, Diverging bar graph, Lollipop graph

Recorded on: 2020-09-28

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/2020_09_29_taylor_swift_beyonce.Rmd)

## Screencast

<div id="yt-player" data-video-id="vYbDyfv_v4Q"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-470">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(470, this)">0:7:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div><span class="badge-packages badge bg-primary">forcats</span></div></div>
    <div class="topic_description">
      <p>Use <code>fct_reorder</code> from the <code>forcats</code> package to reorder <code>title</code> factor levels by sorting along the <code>sales</code> variable in <code>geom_col</code> plot.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-490">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(490, this)">0:8:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">labels</span></div><div><span class="badge-packages badge bg-primary">scales</span></div></div>
    <div class="topic_description">
      <p>Use <code>labels = dollar</code> from the <code>scales</code> package to format the <code>geom_col</code> x-axis values as currency.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-675">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(675, this)">0:11:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">rename_all</span><span class="badge-functions badge bg-info">str_to_lower</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">stringr</span></div></div>
    <div class="topic_description">
      <p>Use <code>rename_all(str_to_lower)</code> to convert variable names to lowercase.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-765">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(765, this)">0:12:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">unnest_tokens</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Use <code>unnest_tokens</code> from the <code>tidytext</code> package to split the lyrics into one-lyric-per-row.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-780">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(780, this)">0:13:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">anti_join</span></div><div><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Use <code>anti_join</code> from the <code>tidytext</code> package to find the most common words int he lyrics without <code>stop_words</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-915">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(915, this)">0:15:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">bind_tf_idf</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Use <code>bind_tf_idf</code> from the <code>tidytext</code> package to determine <code>tf</code> - the proportion each word has in each album and <code>idf</code> - how specific each word is to each particular album.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1065">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1065, this)">0:17:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">reorder_within</span><span class="badge-functions badge bg-info">scale_y_reordered</span><span class="badge-functions badge bg-info">slice_max</span></div><div><span class="badge-packages badge bg-primary">tidytext</span><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Use <code>reorder_within</code> with <code>scale_y_reordered</code> in order to reorder the bars within each <code>facet panel</code>. David replaces <code>top_n</code> with <code>slice_max</code> from the <code>dplyr</code> package in order to show the top 10 words with <code>ties = FALSE</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1245">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1245, this)">0:20:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">bind_log_odds</span></div><div><span class="badge-packages badge bg-primary">tidylo</span></div></div>
    <div class="topic_description">
      <p>Use <code>bind_log_odds</code> from the <code>tidylo</code> package to calculate the <code>log odds ratio</code> of album and words, that is how much more common is the word in a specific album than across all the other albums.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1390">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1390, this)">0:23:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">filter</span><span class="badge-functions badge bg-info">str_length</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">stringr</span></div></div>
    <div class="topic_description">
      <p>Use <code>filter(str_length(word) &lt;= 3)</code> to come up with a list in order to remove common filler words like <code>ah</code>, <code>uh</code>, <code>ha</code>, <code>ey</code>, <code>eeh</code>, and <code>huh</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1620">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1620, this)">0:27:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">distinct</span><span class="badge-functions badge bg-info">mdy</span><span class="badge-functions badge bg-info">str_remove</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">lubridate</span><span class="badge-packages badge bg-primary">stringr</span></div></div>
    <div class="topic_description">
      <p>Use <code>mdy</code> from the <code>lubridate</code> package and <code>str_remove(released, &quot; \\(.*)&quot;))</code> from the <code>stringr</code> package to parse the dates in the <code>released</code> variable.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1695">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1695, this)">0:28:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">inner_join</span><span class="badge-functions badge bg-info">fct_recode</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">forcats</span></div></div>
    <div class="topic_description">
      <p>Use <code>inner_join</code> from the <code>dplyr</code> package to join <code>taylor_swift_words</code> with <code>release_dates</code>.</p>
<p>David ends up having to use <code>fct_recode</code> since the albums <code>reputation</code> and <code>folklore</code> were nor <code>lowercase</code> in a previous table thus excluding them from the <code>inner_join</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1710">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1710, this)">0:28:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span><span class="badge-functions badge bg-info">geom_col</span></div><div><span class="badge-packages badge bg-primary">forcats</span><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>fct_reorder</code> from the <code>forcats</code> package to reorder <code>album</code> factor levels by sorting along the <code>released</code> variable to be used in the <code>faceted</code> <code>geom_col</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2080">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2080, this)">0:34:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">bind_rows</span><span class="badge-functions badge bg-info">unnest_tokens</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Use <code>bind_rows</code> from hte <code>dplyr</code> package to bind <code>ts</code> with <code>beyonce</code> with <code>unnest_tokens</code> from the <code>tidytext</code> package to get one lyric per row per artist.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2320">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2320, this)">0:38:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">bind_log_odds</span></div><div><span class="badge-packages badge bg-primary">tidylo</span></div></div>
    <div class="topic_description">
      <p>Use <code>bind_log_odds</code> to figure out which words are more likely to come from a Taylor Swift or Beyonce song?</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2470">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2470, this)">0:41:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">slice_max</span><span class="badge-functions badge bg-info">geom_col</span><span class="badge-functions badge bg-info">ifelse</span><span class="badge-functions badge bg-info">fct_reorder</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">ggplot2</span><span class="badge-packages badge bg-primary">forcats</span></div></div>
    <div class="topic_description">
      <p>Use <code>slice_max</code> from the <code>dplyr</code> package to select the top 100 words by <code>num_words_total</code> and then the top 25 by <code>log_odds_weighted</code>. Results are used to create a diverging bar chart showing which words are most common between Beyonce and Taylor Swift songs.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2680">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2680, this)">0:44:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">scale_x_continuous</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>scale_x_continuous</code> to make the <code>log_odds_weighted</code> scale more interpretable.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3045">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3045, this)">0:50:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_col</span><span class="badge-functions badge bg-info">geom_point</span><span class="badge-functions badge bg-info">geom_vline</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Take the previous plot and turn it into a <code>lollipop graph</code> with <code>geom_point(aes(size = num_words_total, color = direction))</code></p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3185">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3185, this)">0:53:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">ifelse</span></div><div><span class="badge-packages badge bg-primary">base</span></div></div>
    <div class="topic_description">
      <p>Use <code>ifelse</code> to change the <code>1x</code> value on the x-axis to <code>same</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3255">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3255, this)">0:54:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pivot_wider</span><span class="badge-functions badge bg-info">clean_names</span><span class="badge-functions badge bg-info">geom_abline</span><span class="badge-functions badge bg-info">geom_point</span><span class="badge-functions badge bg-info">slice_max</span><span class="badge-functions badge bg-info">scale_y_log_10</span><span class="badge-functions badge bg-info">scale_x_log_10</span><span class="badge-functions badge bg-info">geom_text</span></div><div><span class="badge-packages badge bg-primary">tidyr</span><span class="badge-packages badge bg-primary">ggplot2</span><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Create a <code>geom_point</code> with <code>geom_abline</code> to show the most popular words they use in common.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3715">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3715, this)">1:01:55</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast.</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
