---
title: |
  Big Mac Index
description: |
  Data manipulation, Pairwise correlation
date: 2020-12-21
date-format: long
aliases:
  - "Big Mac Index.html"
---

Notable topics: Data manipulation, Pairwise correlation

Recorded on: 2020-12-21

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/2020_12_22_big_mac_index.Rmd)

## Screencast

<div id="yt-player" data-video-id="pxJ5wtxL5Kw"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-345">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(345, this)">0:5:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">add_count</span></div><div><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Use the <code>add_count</code> function from the <code>dplyr</code> package with <code>name = &quot;country_total&quot;</code> to count the number of observations by group in the <code>name</code> variable.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-355">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(355, this)">0:5:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">filter</span><span class="badge-functions badge bg-info">max</span></div><div><span class="badge-packages badge bg-primary">dplyr</span><span class="badge-packages badge bg-primary">base</span></div></div>
    <div class="topic_description">
      <p>Use <code>filter</code> from the <code>dplyr</code> package with <code>country_total == max(country_total)</code> to filter the data for countries where every data point is provided.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-390">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(390, this)">0:6:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">rename</span></div><div><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Use the <code>rename</code> function from the <code>dplyr</code> package to rename the <code>name</code> variable to <code>country_name</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-405">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(405, this)">0:6:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">theme</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>theme(legend.position = &quot;none&quot;)</code> to hide the legend generated by the <code>geom_line</code> plot.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-420">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(420, this)">0:7:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">expand_limits</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use the <code>expand_limits</code> function from the <code>ggplot2</code> package with <code>y = 0</code> so that each <code>facet panel</code> has a y-axis that starts at the same point, in this case 0.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-510">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(510, this)">0:8:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div><span class="badge-packages badge bg-primary">forcats</span></div></div>
    <div class="topic_description">
      <p>Reorder <code>facet panels</code> using the <code>fct_reorder</code> from the <code>forcats</code> package with a function passed in to the <code>.fun</code> argument to calculate the ratio between <code>max</code> and <code>min</code> values in the <code>local_price</code> variable.  At 12:00, David changes from using <code>max</code> and <code>min</code> to <code>last</code> and <code>first</code> to calculate the <code>Big Mac inflation rate</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-800">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(800, this)">0:13:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">scale_x_log10</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>scale_x_log10</code> from the <code>ggplot2</code> package to change the <code>breaks</code> for the <code>x-axis</code> while also applying a <code>log10</code> tranformation.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-905">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(905, this)">0:15:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span><span class="badge-functions badge bg-info">paste0</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span><span class="badge-packages badge bg-primary">base</span></div></div>
    <div class="topic_description">
      <p>Use <code>geom_text</code> from the from the <code>ggplot2</code> with <code>paste0</code> package to add labels to each bar in the plot indicating how many time <code>X</code> the price of a Big Mac increased from 2000 to 2020.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1690">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1690, this)">0:28:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_line</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Add two lines to a plot using 2 <code>geom_line</code>  with  <code>color =</code> argument and <code>y=</code> argument to distinguish between the two lines.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2045">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2045, this)">0:34:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_hline</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>geom_hline</code> from the <code>ggplot2</code> package to add horizontal reference line to each facet panel.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2140">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2140, this)">0:35:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">theme</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>theme</code> from the <code>ggplot2</code> package with <code>axis.text.x = element_text(angle = 90, hjust = 1)</code> to rmake the x-axis labels horizontal in order to avoid overcrowding.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2305">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2305, this)">0:38:25</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span><span class="badge-functions badge bg-info">geom_text_repel</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span><span class="badge-packages badge bg-primary">ggrepel</span></div></div>
    <div class="topic_description">
      <p>Use <code>geom_text</code> to add country names to each point in <code>geom_point</code> plot. David then opts to use <code>geom_text_repel</code> from the <code>ggrepel</code> package instead to avoid overcrowding.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2320">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2320, this)">0:38:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_smooth</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>geom_smooth</code> from the <code>ggplot2</code> package with <code>lm</code> smoothing method to help show the linear trend when comparing <code>gdp_dollar</code> to <code>usd_raw</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2820">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2820, this)">0:47:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">transition_manual</span><span class="badge-functions badge bg-info">transition_time</span></div><div><span class="badge-packages badge bg-primary">gganimate</span></div></div>
    <div class="topic_description">
      <p>Use the <code>gganimate</code> package to animate the <code>GDP per capital</code> versus <code>adjusted big mac index relative to USD</code> over time.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3185">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3185, this)">0:53:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_to_upper</span><span class="badge-functions badge bg-info">str_remove</span></div><div><span class="badge-packages badge bg-primary">stringr</span></div></div>
    <div class="topic_description">
      <p>Use <code>str_to_upper</code> and <code>str_remove</code> to remove <code>_adjusted</code> from <code>base_currency</code> while uppercasing the characters that remain.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3485">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3485, this)">0:58:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pairwise_cor</span></div><div><span class="badge-packages badge bg-primary">widyr</span></div></div>
    <div class="topic_description">
      <p>Use <code>pairwise_cor</code> from the <code>widyr</code> package to perform <code>pairwise correlation</code> to figure out which countries Big Mac prices tend to move together over time.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3650">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3650, this)">1:00:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Screencast summary.</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
