---
title: "Bird Collisions"
description: "Bootstrapping"
date: 2019-05-03
date-format: long
---

Notable topics: Bootstrapping

Recorded on: 2019-05-03

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/bird-collisions.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:45

Analyzing when NAs appear in a dimension

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=165" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:30

Looking at multiple categorical variable at the same time by gathering them into one column and eventually graphing each as a different facet

gather

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=450" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:30

Re-order facet graphs according to which ones have the fewest categories in them to ones that have the most

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=570" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:45

Geometric mean for estimating counts when there are a lot of low values (1-3 bird collisions, in this case)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=1245" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:15

Filling in "blank" observations where there were no observations made

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=1395" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:00

Using log+1 to convert a dimension with values of 0 into a log scale

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=1620" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:00

Adding confidence bounds for data using a geometric mean (where he first gets the idea of bootstrapping)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=1740" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:00

Actual coding of bootstrap starts

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=1920" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:38:30

Adding confidence bounds using bootstrap data

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=2310" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:00

Investigating potential confounding variables

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=2520" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:15

Discussing approaches to dealing with confounding variables

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=2655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:45

Using complete function to get explicit NA values

complete

NA



<iframe class="video" src="https://www.youtube.com/embed/zjWm__nFLXI?start=2805" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

