---
title: "Board Game Reviews"
description: "LASSO regression (glmnet package)"
date: 2019-03-15
date-format: long
---

Notable topics: LASSO regression (glmnet package)

Recorded on: 2019-03-15

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/board-games.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:50

Starting EDA (exploratory data analysis) with counts of categorical variables

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:25

Specifying scale_x_log10 function's breaks argument to get sensisble tick marks for time on histogram

scale_x_log10

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=445" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:45

Tweaking geom_histogram function's binwidth argument to get something that makes sense for log scale

geom_histogram

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=525" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:10

Using separate_rows to break down comma-separated values for three different categorical variables

separate_rows

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=610" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:55

Using top_n to get top 20 observations from each of several categories (not quite right, fixed at 17:47)

top_n

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=955" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:15

Troubleshooting various issues with facetted graph (e.g., ordering, values appearing in multiple categories)

facet_wrap

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=975" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:55

Starting prediction of average rating with a linear model

lm

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1195" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:50

Splitting data into train/test sets (training/holdout)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1250" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:55

Investigating relationship between max number of players and average rating (to determine if it should be in linear model)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1375" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:05

Exploring average rating over time ("Do newer games tend to be rated higher/lower?")

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1505" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:35

Discussing necessity of controlling for year a game was published in the linear model

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:30

Non-model approach to exploring relationship between game features (e.g., card game, made in Germany) on average rating

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1710" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:50

Using geom_boxplot function to create boxplot of average ratings for most common game features

geom_boxplot

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=1850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:05

Using unite function to combine multiple variables into one

unite

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2045" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:25

Introducing Lasso regression as good option when you have many features likely to be correlated with one another

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2245" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:38:15

Writing code to set up Lasso regression using glmnet and tidytext packages

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2295" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:05

Adding average rating to the feature matrix (warning: method is messy)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2405" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:40

Using setdiff function to find games that are in one set, but not in another (while setting up matrix for Lasso regression)

setdiff

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2500" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:15

Spotting the error stemming from the step above (calling row names from the wrong data)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:45

Explaining what a Lasso regression does, including the penalty parameter lambda

glmnet

glmnet



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2745" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:35

Using a cross-validated Lasso model to choose the level of the penalty parameter (lambda)

cv.glmnet

glmnet



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=2915" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:35

Adding non-categorical variables to the Lasso model to control for them (e.g., max number of players)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=3095" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:55:15

Using unite function to combine multiple variables into one, separated by a colon

unite

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=3315" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:45

Graphing the top 20 coefficients in the Lasso model that have the biggest effect on predicted average rating

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=3525" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:55

Mentioning the yardstick package as a way to evaluate the model's performance

NA

yardstick



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=3655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:01:15

Discussing drawbacks of linear models like Lasso (can't do non-linear relationships or interaction effects)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/qirKGdQvy9U?start=3675" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

