---
title: "Broadway Musicals"
description: "Creating an interactive dashboard with shinymetrics and tidymetrics, moving windows, period aggregation"
date: 2020-04-28
date-format: long
---

Notable topics: Creating an interactive dashboard with shinymetrics and tidymetrics, moving windows, period aggregation

Recorded on: 2020-04-28

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/broadway.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:8:15

Use the `cross_by_periods ` function from the `tidymetrics` package to aggregate data over time (`month`, `quarter`, and `year`) then visualize with `geom_line`.

rename | cross_by_periods

tidymetrics



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=495" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:00

Use the `cross_by_periods ` function from the `tidymetrics`  package with `windows = c(28))` to create a 4-week rolling average across `month`, `quarter`, and `year`.

cross_by_periods

tidymetrics



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=840" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:50

Create and `interactive dashboard` using the `shinymetrics` and `tidymetrics` packages.

use_metrics_scaffold | create_metrics

shinymetrics | Tidaymetrics



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=1310" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:00

Use the `str_remove` function from the `stringr` package to remove matched pattern in a string.

str_remove

stringr



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=1500" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:20

Use the `cross_by_dimensions` function from the `tidymetrics` package which acts as an extended `group_by` that allows complete summaries across each individual dimension and possible combinations.

cross_by_dimensions

tidymetrics



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=1520" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:25

Use the `shinybones` package to create an interactive dashboard to visualize all 3 metrics at the same time.

NA

shinybones



<iframe width="560" height="315" src="https://www.youtube.com/embed/OhY5ZaILRpg?start=2485" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

