---
title: |
  Caribou Locations
description: |
  Maps with `ggplot2`, Calculating distance and speed with `geosphere`
date: 2020-06-22
date-format: long
aliases:
  - "Caribou Locations.html"
---

Notable topics: Maps with `ggplot2`, Calculating distance and speed with `geosphere`

Recorded on: 2020-06-22

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/caribou-locations.Rmd)

## Screencast

<div id="yt-player" data-video-id="7G7SVODhVo4"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-240">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(240, this)">0:4:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">summarize</span><span class="badge-functions badge bg-info">across</span></div><div><span class="badge-packages badge bg-primary">dplyr</span></div></div>
    <div class="topic_description">
      <p>Use <code>summarize</code> and <code>across</code> to calculate the proportion of <code>NA</code> values in the <code>individuals</code> dataset. Note, you do not need to use <code>list()</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-540">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(540, this)">0:9:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">ggplot</span><span class="badge-functions badge bg-info">borders</span></div><div><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>ggplot</code> and <code>borders</code> from the <code>ggplot2</code> package to create a map of <code>Canada</code> with <code>deploy_on_longitude</code> and <code>deploy_on_latitude</code> from the <code>individuals</code> dataset.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-830">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(830, this)">0:13:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">read_sf</span></div><div><span class="badge-packages badge bg-primary">sf</span></div></div>
    <div class="topic_description">
      <p>Import Canada province <code>shapefile</code> using the <code>sf</code> package. [Unsuccessful]</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1500">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1500, this)">0:25:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">min</span><span class="badge-functions badge bg-info">max</span></div><div><span class="badge-packages badge bg-primary">base</span></div></div>
    <div class="topic_description">
      <p>Use <code>min</code> and <code>max</code> from <code>base r </code> within <code>summarize</code> to find out the <code>start</code> and <code>end</code> dates for each caribou in the <code>locations</code> dataset.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1635">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1635, this)">0:27:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">sample</span><span class="badge-functions badge bg-info">geom_path</span></div><div><span class="badge-packages badge bg-primary">base</span><span class="badge-packages badge bg-primary">ggplot2</span></div></div>
    <div class="topic_description">
      <p>Use <code>sample</code> from <code>base r</code> to pick one single caribou at a time then use the subset with <code>geom_path</code> from <code>ggplot2</code> to track the path a that caribou takes over time.  <code>color = factor(floor_date(timestamp, &quot;quarter&quot;)</code> is used to color the path according to what quarter the observation occured in.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2115">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2115, this)">0:35:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">as.Date</span><span class="badge-functions badge bg-info">floor_date</span></div><div><span class="badge-packages badge bg-primary">base</span><span class="badge-packages badge bg-primary">lubridate</span></div></div>
    <div class="topic_description">
      <p>Use <code>as.Date</code> from <code>base r</code> and <code>floor_date</code> from the <code>lubridate</code> package to convert <code>timestamp</code> variable into quarters then <code>facet_wrap</code> the previous plot by <code>quarter</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2235">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2235, this)">0:37:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">difftime</span><span class="badge-functions badge bg-info">lag</span></div><div><span class="badge-packages badge bg-primary">base</span></div></div>
    <div class="topic_description">
      <p>Within <code>mutate</code>, use <code>as.numeric(difftime(timestamp, lag(timestamp), unit = &quot;hours&quot;))</code>  from <code>base r</code> to figure out the gap in time between observations.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2585">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2585, this)">0:43:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">distHaversine</span><span class="badge-functions badge bg-info">cbind</span></div><div><span class="badge-packages badge bg-primary">geosphere</span></div></div>
    <div class="topic_description">
      <p>Use <code>distHaversine</code> from the <code>geosphere</code> package to calculate distance in <code>km</code> then convert it to speed in <code>kph</code>.</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3600">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3600, this)">1:00:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of dataset.</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
