---
title: |
  College Majors and Income
description: |
  Graphing for EDA (Exploratory Data Analysis)
date: 2018-10-15
date-format: long
aliases:
  - "College Majors and Income.html"
---

Notable topics: Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2018-10-15

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/college-majors.Rmd)

## Screencast

<div id="yt-player" data-video-id="nx5yhXAQLxw"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-105">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(105, this)">0:1:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">read_csv</span></div><div></div></div>
    <div class="topic_description">
      <p>Using read_csv function to import data directly from Github to R (without cloning the repository)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-440">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(440, this)">0:7:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_histogram</span><span class="badge-functions badge bg-info">geom_boxplot</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a histogram (geom_histogram), then a boxplot (geom_boxplot), to explore the distribution of salaries</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-535">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(535, this)">0:8:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_reorder function to sort boxplot of college majors by salary</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-575">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(575, this)">0:9:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">dollar_format</span></div><div><span class="badge-packages badge bg-primary">scales</span></div></div>
    <div class="topic_description">
      <p>Using dollar_format function from scales package to convert scientific notation to dollar format (e.g., &quot;4e+04&quot; becomes &quot;$40,000&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-850">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(850, this)">0:14:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_point</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a dotplot (geom_point) of 20 top-earning majors (includes adjusting axis, using the colour aesthetic, and adding error bars)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1065">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1065, this)">0:17:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_to_title</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_to_title function to convert string from ALL CAPS to Title Case</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1245">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1245, this)">0:20:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Creating a Bland-Altman graph to explore relationship between sample size and median salary</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1305">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1305, this)">0:21:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text_repel</span></div><div><span class="badge-packages badge bg-primary">ggrepel</span></div></div>
    <div class="topic_description">
      <p>Using geom_text_repel function from ggrepel package to get text labels on scatter plot points</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1710">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1710, this)">0:28:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">count</span></div><div></div></div>
    <div class="topic_description">
      <p>Using count function's wt argument to specify what should be counted (default is number of rows)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1800">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1800, this)">0:30:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Spicing up a dull bar graph by adding a redundant colour aesthetic (trick from Julia Silge)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2180">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2180, this)">0:36:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting to explore relationship between gender and salary</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2230">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2230, this)">0:37:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_col</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a stacked bar graph (geom_col) of gender breakdown within majors</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2415">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2415, this)">0:40:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">summarise_at</span></div><div></div></div>
    <div class="topic_description">
      <p>Using summarise_at to aggregate men and women from majors into categories of majors</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2730">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2730, this)">0:45:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_point</span></div><div></div></div>
    <div class="topic_description">
      <p>Graphing scatterplot (geom_point) of share of women and median salary</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2830">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2830, this)">0:47:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_smooth</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_smooth function to add a line of best fit to scatterplot above</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2920">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2920, this)">0:48:40</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of why not to aggregate first when performing a statistical test (including explanation of Simpson's Paradox)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2995">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2995, this)">0:49:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_smooth</span></div><div></div></div>
    <div class="topic_description">
      <p>Fixing geom_smooth so that we get one overall line while still being able to map to the colour aesthetic</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3070">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3070, this)">0:51:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">lm</span></div><div></div></div>
    <div class="topic_description">
      <p>Predicting median salary from share of women with weighted linear regression (to take sample sizes into account)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3365">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3365, this)">0:56:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">nest</span><span class="badge-functions badge bg-info">tidy</span></div><div><span class="badge-packages badge bg-primary">broom</span></div></div>
    <div class="topic_description">
      <p>Using nest function and tidy function from the broom package to apply a linear model to many categories at once</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3485">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3485, this)">0:58:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">p.adjust</span></div><div></div></div>
    <div class="topic_description">
      <p>Using p.adjust function to adjust p-values to correct for multiple testing (using FDR, False Discovery Rate)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3890">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3890, this)">1:04:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Showing how to add an appendix to an RMarkdown file with code that doesn't run when compiled</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4140">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4140, this)">1:09:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_lump</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_lump function to aggregate major categories into the top four and an &quot;Other&quot; category</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4205">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4205, this)">1:10:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding sample size to the size aesthetic within the aes function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4250">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4250, this)">1:10:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">ggplotly</span></div><div><span class="badge-packages badge bg-primary">plotly</span></div></div>
    <div class="topic_description">
      <p>Using ggplotly function from plotly package to create an interactive scatterplot (tooltips appear when moused over)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4555">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4555, this)">1:15:55</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring IQR (Inter-Quartile Range) of salaries by major</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
