---
title: "College Majors and Income"
description: "Graphing for EDA (Exploratory Data Analysis)"
date: 2018-10-15
date-format: long
---

Notable topics: Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2018-10-15

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/college-majors.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:1:45

Using read_csv function to import data directly from Github to R (without cloning the repository)

read_csv

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=105" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:20

Creating a histogram (geom_histogram), then a boxplot (geom_boxplot), to explore the distribution of salaries

geom_histogram | geom_boxplot

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=440" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:55

Using fct_reorder function to sort boxplot of college majors by salary

fct_reorder

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=535" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:35

Using dollar_format function from scales package to convert scientific notation to dollar format (e.g., "4e+04" becomes "$40,000")

dollar_format

scales



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=575" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:10

Creating a dotplot (geom_point) of 20 top-earning majors (includes adjusting axis, using the colour aesthetic, and adding error bars)

geom_point

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:45

Using str_to_title function to convert string from ALL CAPS to Title Case

str_to_title

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=1065" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:45

Creating a Bland-Altman graph to explore relationship between sample size and median salary

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=1245" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:45

Using geom_text_repel function from ggrepel package to get text labels on scatter plot points

geom_text_repel

ggrepel



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=1305" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:30

Using count function's wt argument to specify what should be counted (default is number of rows)

count

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=1710" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:00

Spicing up a dull bar graph by adding a redundant colour aesthetic (trick from Julia Silge)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=1800" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:36:20

Starting to explore relationship between gender and salary

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2180" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:10

Creating a stacked bar graph (geom_col) of gender breakdown within majors

geom_col

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2230" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:15

Using summarise_at to aggregate men and women from majors into categories of majors

summarise_at

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2415" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:30

Graphing scatterplot (geom_point) of share of women and median salary

geom_point

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2730" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:10

Using geom_smooth function to add a line of best fit to scatterplot above

geom_smooth

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2830" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:40

Explanation of why not to aggregate first when performing a statistical test (including explanation of Simpson's Paradox)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2920" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:55

Fixing geom_smooth so that we get one overall line while still being able to map to the colour aesthetic

geom_smooth

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=2995" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:10

Predicting median salary from share of women with weighted linear regression (to take sample sizes into account)

lm

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=3070" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:05

Using nest function and tidy function from the broom package to apply a linear model to many categories at once

nest | tidy

broom



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=3365" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:05

Using p.adjust function to adjust p-values to correct for multiple testing (using FDR, False Discovery Rate)

p.adjust

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=3485" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:04:50

Showing how to add an appendix to an RMarkdown file with code that doesn't run when compiled

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=3890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:09:00

Using fct_lump function to aggregate major categories into the top four and an "Other" category

fct_lump

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=4140" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:10:05

Adding sample size to the size aesthetic within the aes function

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=4205" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:10:50

Using ggplotly function from plotly package to create an interactive scatterplot (tooltips appear when moused over)

ggplotly

plotly



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=4250" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:15:55

Exploring IQR (Inter-Quartile Range) of salaries by major

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/nx5yhXAQLxw?start=4555" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

