---
title: "CORD-19 Data Package"
description: "R package development and documentation-writing"
date: 2020-03-19
date-format: long
---

Notable topics: R package development and documentation-writing

Recorded on: 2020-03-19

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/cord-19.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:1:10

Overview of JSON files with the data David will make a package of

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=70" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:3:05

Starting to create a new package with "New Project" in RStudio

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=185" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:5:40

Creating a file to reference the license for the dataset

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=340" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:25

Using use_data_raw function from usethis package to set up a folder structure and preliminary function for raw data

use_data_raw

usethis



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=445" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:30

Explanation that we want to limit the number of packages we load when building a package (e.g., no library(tidyverse) )

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=510" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:00

Using use_package function from usethis package to add "Suggested packages"

use_package

usethis



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=540" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:15

Reviewing import and cleaning code already completed

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=615" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:55

Using roxygen2 package to write documentation

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=895" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:35

More documentation writing

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:24:50

Using use_data function from usethis package to create a folder structure and datafile for (finished/cleaned) data

use_data

usethis



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1490" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:10

Making a mistake clicking "Install and Restart" button on the "Build" tab (because of huge objects in the environment) (see 26:50 for alternative)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1570" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:50

Using load_all function from devtrools package as an alternative to "Install and Restart" from above step

load_all

devtools



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1610" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:35

Using document function from devtools package to process written documentation

document

devtools



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:20

De-duplicating paper data in a way the keeps records that have fewer missing values than other records for the same paper

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=1940" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:50

Using use_data function with its overwrite argument to overwrite existing data

use_data

usethis



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=2390" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:30

Writing documentation for paragraphs data

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=2850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:55

Testing an install of the package

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=3475" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:59:30

Adding link to code in documentation

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=3570" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:03:00

Writing examples of how to use the package (in documentation)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=3780" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:08:45

Discussion of outstanding items that David hasn't done yet (e.g., readme, vignettes, tests)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4125" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:09:20

Creating a simple readme, including examples, with use_readme_rmd function from usethis package

use_readme_rmd

usethis



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4160" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:16:10

Using knit function from the knitr package to knit the readme into a markdown file

knit

knitr



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4570" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:17:10

Creating a GitHub repository to host the package (includes how to commit to a GitHub repo using RStudio's GUI)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:18:15

Explanation that version 0.0.0.9000 means that the package is in early development

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4695" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:20:30

Actually creating the GitHub repository

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4830" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:22:25

Overview of remaining tasks

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/F4oUJp76KUY?start=4945" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

