---
title: |
  COVID-19 Open Research Dataset (CORD-19)
description: |
  JSON formatted data
date: 2020-03-18
date-format: long
aliases:
  - "COVID-19 Open Research Dataset (CORD-19).html"
---

Notable topics: JSON formatted data

Recorded on: 2020-03-18

Timestamps by: Alex Cookson

[View code](NA)

## Screencast

<div id="yt-player" data-video-id="-5HYdBq_PTM"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-55">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(55, this)">0:0:55</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Disclaimer that David's not an epidemiologist</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-175">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(175, this)">0:2:55</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Overview of dataset</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-470">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(470, this)">0:7:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">dir</span></div><div></div></div>
    <div class="topic_description">
      <p>Using dir function with its full.names argument to get file paths for all files in a folder</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-585">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(585, this)">0:9:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Inspecting JSON-formatted data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-640">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(640, this)">0:10:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">hoist</span></div><div></div></div>
    <div class="topic_description">
      <p>Introducing hoist function as a way to deal with nested lists (typical for JSON data)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-700">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(700, this)">0:11:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">hoist</span></div><div></div></div>
    <div class="topic_description">
      <p>Continuing to use the hoist function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-790">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(790, this)">0:13:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pluck</span></div><div></div></div>
    <div class="topic_description">
      <p>Brief explanation of pluck specification</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-995">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(995, this)">0:16:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">object.size</span></div><div></div></div>
    <div class="topic_description">
      <p>Using object.size function to check size of json data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1060">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1060, this)">0:17:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">map_chr</span><span class="badge-functions badge bg-info">str_c</span></div><div></div></div>
    <div class="topic_description">
      <p>Using map_chr and str_c functions together to combine paragraphs of text in a list into a single character string</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1200">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1200, this)">0:20:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">unnest_tokens</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Using unnest_tokens function from tidytext package to split full paragraphs into individual words</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1370">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1370, this)">0:22:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Overview of scispaCy package for Python, which has named entity recognition features</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1480">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1480, this)">0:24:40</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">spacyr</span></div></div>
    <div class="topic_description">
      <p>Introducting spacyr package, which is a R wrapper around the Python scispaCy package</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1730">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1730, this)">0:28:50</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Showing how tidytext can use a custom tokenization function (David uses spacyr package's named entity recognition)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1940">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1940, this)">0:32:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">tokenize_words</span></div><div><span class="badge-packages badge bg-primary">tokenizers</span></div></div>
    <div class="topic_description">
      <p>Demonstrating the tokenize_words function from the tokenizers package</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2220">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2220, this)">0:37:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">unnest_tokens</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Actually using a custom tokenizer in unnest_tokens function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2385">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2385, this)">0:39:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">sample_n</span></div><div></div></div>
    <div class="topic_description">
      <p>Using sample_n function to get a random sample of n rows</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2605">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2605, this)">0:43:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;What are groups of words that tend to occur together?&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2670">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2670, this)">0:44:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pairwise_cor</span></div><div><span class="badge-packages badge bg-primary">widyr</span></div></div>
    <div class="topic_description">
      <p>Using pairwise_cor from widyr package to find correlation between named entities</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2740">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2740, this)">0:45:40</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">ggraph</span><span class="badge-packages badge bg-primary">igraph</span></div></div>
    <div class="topic_description">
      <p>Using ggraph and igraph packages to create a network plot</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3125">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3125, this)">0:52:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting to look at papers' references</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3210">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3210, this)">0:53:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">unnest_wider</span></div><div></div></div>
    <div class="topic_description">
      <p>Using unnest_longer then unnest_wider function to convert lists into a tibble</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3570">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3570, this)">0:59:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_trunc</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_trunc function to truncate long character strings to a certain number of characters</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3985">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3985, this)">1:06:25</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">glue</span></div><div><span class="badge-packages badge bg-primary">glue</span></div></div>
    <div class="topic_description">
      <p>Using glue function for easy combination of strings and R code</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4755">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4755, this)">1:19:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
