---
title: |
  CRAN Package Code
description: |
  Graphing for EDA (Exploratory Data Analysis)
date: 2019-12-29
date-format: long
aliases:
  - "CRAN Package Code.html"
---

Notable topics: Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2019-12-29

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/cran-code.Rmd)

## Screencast

<div id="yt-player" data-video-id="dr4qw8o0nYU"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-270">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(270, this)">0:4:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summarizing many things by language (e.g., lines of code, comment/code ratio)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-575">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(575, this)">0:9:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">gather</span></div><div></div></div>
    <div class="topic_description">
      <p>Using gather function to consolidate multiple metrics into one dimension, then visualizing by facetting by metric</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-680">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(680, this)">0:11:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">facet_wrap</span></div><div></div></div>
    <div class="topic_description">
      <p>Setting ncol = 1 within facet_wrap function to get facetted graphs to stack vertically</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-690">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(690, this)">0:11:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">reorder_within</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Using reorder_within function (tidytext package) to properly reorder factors within each facet</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-960">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(960, this)">0:16:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_text label to add language name as label to scatter points</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1200">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1200, this)">0:20:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Completing preliminary overview and looking at distribution of R code in packages</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1575">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1575, this)">0:26:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_extract</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_extract to extract only letters and names from character vector (using regex)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2040">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2040, this)">0:34:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">guides</span></div><div></div></div>
    <div class="topic_description">
      <p>Re-ordering the order of categorical variables in the legend using guides function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2160">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2160, this)">0:36:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Investigating comment/code ratio</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2585">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2585, this)">0:43:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Importing additional package data (looking around for a bit, then starting to actually import ~46:00)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3280">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3280, this)">0:54:40</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Importing even more additional data (available packages)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3470">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3470, this)">0:57:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">separate_rows</span></div><div></div></div>
    <div class="topic_description">
      <p>Using separate_rows function to separate delimited values</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3525">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3525, this)">0:58:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">extract</span></div><div></div></div>
    <div class="topic_description">
      <p>Using extract function and regex to pull out specific types of characters from a string</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3935">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3935, this)">1:05:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
