---
title: "Global Crop Yields"
description: "Interactive Shiny Dashboard"
date: 2020-09-01
date-format: long
---

Notable topics: Interactive Shiny Dashboard

Recorded on: 2020-09-01

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/2020_09_01_crop_yields.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:03:35

Using `rename` to shorten column name

rename

dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=215" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:06:40

Using `rename_all` with `str_remove` and regex to remove characters in column name

rename_all | str_remove

dplyr | string



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=400" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:07:40

Using `pivot_longer` to change data from wide to long

pivot_longer

tidyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=460" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:08:25

Create a faceted `geom_line` chart

geom_line | facet_wrap

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=505" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:09:40

Using `fct_reorder` to reorder facet panels in ascending order

fct_reorder

forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=580" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:50

Create an interactive `Shiny` dashboard

write_rds | inputPanel | renderPlot

shiny | dplyr | ggplot2 | forcats |
stringr | plotly



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=710" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:20

Create a faceted `geom_line` chart with `add_count` and `filter(n = max(x))` to subset the data for crops that have observations in every year

geom_line

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=2000" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:36:50

Create a faceted `geom_point` chart showing the crop yields at start and end over a 50 year period (1968 start date and 2018 end date)

geom_point | geom_abline

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=2210" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:00

Create a `geom_boxplot` to visualize the distribution of yield ratios for the different crops to see how efficiency has increased across countries

geom_boxplot

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=2700" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:00

Create a `geom_col` chart to visualize the median yield ratio for each crop

geom_col

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=2760" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:50

Create a `geom_point` chart to visualize efficiency imporvement for each country for a specific crop (yield start / yield ratio)

geom_point | geom_text_repel

ggplot2 | ggrepel



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=2870" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:50:25

Using the `countrycode` package to color `geom_point` chart by continent names

countrycode | geom_hline | geom_text_repel

countrycode | ggplot2 | ggrepel



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=3025" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:50

Summary of screencast

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/0uqAhIiK9Rc?start=3410" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

