---
title: "Horror Movie Profits"
description: "Graphing for EDA (Exploratory Data Analysis)"
date: 2018-10-23
date-format: long
---

Notable topics: Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2018-10-23

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/horror-movie-ratings.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:50

Using parse_date function from lubridate package to convert date formatted as character to date class (should have used mdy function though)

parse_date

lubridate



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:45

Using fct_lump function to aggregate distributors into top 6 (by number of movies) and and "Other" category

fct_lump

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=465" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:50

Investigating strange numbers in the data and discovering duplication

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=530" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:40

Using problems function to look at parsing errors when importing data

problems

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=760" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:35

Using arrange and distinct function and its .keep_all argument to de-duplicate observations

arrange | distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=875" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:10

Using geom_boxplot function to create a boxplot of budget by distributor

goem_boxplot

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:20

Using floor function to bin release years into decades (e.g., "1970" and "1973" both become "1970")

floor

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1160" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:30

Using summarise_at function to apply the same function to multiple variables at the same time

summarise_at

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1290" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:24:10

Using geom_line to visualize multiple metrics at the same time

geom_line

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1450" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:00

Using facet_wrap function to graph small multiples of genre-budget boxplots by distributor

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1560" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:35

Starting analysis of profit ratio of movies

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1715" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:50

Using paste0 function in a custom function to show labels of multiple (e.g., "4X" or "6X" to mean "4 times" or "6 times")

paste0

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=1970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:20

Starting analysis of the most common genres over time

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=2480" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:55

Starting analysis of the most profitable individual horror movies

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=2755" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:45

Using paste0 function to add release date of movie to labels in a bar graph

paste0

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=3105" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:25

Using geom_text function, along with its check_overlap argument, to add labels to some points on a scatterplot

geom_text

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=3205" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:10

Using ggplotly function from plotly package to create an interactive scatterplot

ggplotly

plotly



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=3490" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:55

Reviewing unexplored areas of investigation

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/3-DRwg9yeNA?start=3655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

