---
title: "Media Franchise Revenue"
description: "Data manipulation (especially re-ordering factors)"
date: 2019-06-22
date-format: long
---

Notable topics: Data manipulation (especially re-ordering factors)

Recorded on: 2019-06-22

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/media-franchises.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:9:15

Explaining use of semi_join function to aggregate and filter groups

semi_join

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=555" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:00

Putting the largest categories on the bottom of a stacked bar chart

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=660" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:30

Using glue function as alternative to paste for combining text, plus good explanation of it

glue

glue



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=870" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:30

Multiple re-ordering using fct_reorder function of facetted graph (he works through several obstacles)

fct_reorder

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:40

Re-ordering the position of facetted graphs so that highest total revenue is at top left

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1240" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:00

Investigating relationship between year created and revenue

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1560" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:40

Creating scatter plot with points scaled by size and labelled points (geom_text function)

geom_text

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1600" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:30

Summary of screencast up to this point

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1770" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:50

Starting analysis original media of franchise (e.g., novel, video game, animated film) and revenue type (e.g., box office, merchandise)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=1790" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:35

Graphing original media and revenue category as facetted bar plot with lots of reordering (ends at around 38:40)

fct_reorder

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2015" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:30

Alternative visualization of original media/revenue category using heat map

geom_tile

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2430" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:20

Using scale_fill_gradient2 function to specify custom colour scale

scale_fill_gradient2

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2480" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:05

Getting rid of gridlines in graph using theme function's panel.grid argument

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2525" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:05

Using fct_rev function to reverse levels of factors

fct_rev

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2645" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:35

Fixing overlapping axis text with tweaks to theme function's axis.text argument

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2675" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:05

Reviewing visualization that inspired this dataset

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2765" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:25

Adding text of total revenue to the end of each bar in a previous graph

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=2845" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:50:20

Using paste0 function at add a "B" (for "billions") to the end of text labels on graph

paste0

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=3020" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:35

Using expand_limits functions to give more space for text labels not to get cut off

expand_limits

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=3095" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:45

Summary of screencast

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/1xsbTs9-a50?start=3225" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

