---
title: |
  Media Franchise Revenue
description: |
  Data manipulation (especially re-ordering factors)
date: 2019-06-21
date-format: long
aliases:
  - "Media Franchise Revenue.html"
---

Notable topics: Data manipulation (especially re-ordering factors)

Recorded on: 2019-06-21

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/media-franchises.Rmd)

## Screencast

<div id="yt-player" data-video-id="1xsbTs9-a50"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-555">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(555, this)">0:9:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">semi_join</span></div><div></div></div>
    <div class="topic_description">
      <p>Explaining use of semi_join function to aggregate and filter groups</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-660">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(660, this)">0:11:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Putting the largest categories on the bottom of a stacked bar chart</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-870">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(870, this)">0:14:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">glue</span></div><div><span class="badge-packages badge bg-primary">glue</span></div></div>
    <div class="topic_description">
      <p>Using glue function as alternative to paste for combining text, plus good explanation of it</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1170">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1170, this)">0:19:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Multiple re-ordering using fct_reorder function of facetted graph (he works through several obstacles)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1240">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1240, this)">0:20:40</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Re-ordering the position of facetted graphs so that highest total revenue is at top left</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1560">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1560, this)">0:26:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Investigating relationship between year created and revenue</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1600">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1600, this)">0:26:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating scatter plot with points scaled by size and labelled points (geom_text function)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1770">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1770, this)">0:29:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast up to this point</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1790">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1790, this)">0:29:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting analysis original media of franchise (e.g., novel, video game, animated film) and revenue type (e.g., box office, merchandise)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2015">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2015, this)">0:33:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Graphing original media and revenue category as facetted bar plot with lots of reordering (ends at around 38:40)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2430">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2430, this)">0:40:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_tile</span></div><div></div></div>
    <div class="topic_description">
      <p>Alternative visualization of original media/revenue category using heat map</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2480">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2480, this)">0:41:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">scale_fill_gradient2</span></div><div></div></div>
    <div class="topic_description">
      <p>Using scale_fill_gradient2 function to specify custom colour scale</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2525">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2525, this)">0:42:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Getting rid of gridlines in graph using theme function's panel.grid argument</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2645">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2645, this)">0:44:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_rev</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_rev function to reverse levels of factors</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2675">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2675, this)">0:44:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Fixing overlapping axis text with tweaks to theme function's axis.text argument</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2765">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2765, this)">0:46:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Reviewing visualization that inspired this dataset</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2845">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2845, this)">0:47:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding text of total revenue to the end of each bar in a previous graph</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3020">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3020, this)">0:50:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">paste0</span></div><div></div></div>
    <div class="topic_description">
      <p>Using paste0 function at add a &quot;B&quot; (for &quot;billions&quot;) to the end of text labels on graph</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3095">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3095, this)">0:51:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">expand_limits</span></div><div></div></div>
    <div class="topic_description">
      <p>Using expand_limits functions to give more space for text labels not to get cut off</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3225">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3225, this)">0:53:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
