---
title: "NCAA Women's Basketball"
description: "Heatmap, Correlation analysis"
date: 2020-10-06
date-format: long
---

Notable topics: Heatmap, Correlation analysis

Recorded on: 2020-10-06

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/2020_10_06_ncaa_womens_basketball.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:15:00

Use `fct_relevel` from the `forcats` package to order the factor levels for the `tourney_finish` variable.

fct_relevel

forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=900" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:35

Use `geom_tile` from the `ggplot2` package to create a `heatmap` to show how far a particular seed ends up going in the tournament.

geom_tile | scale_fill_gradient2

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=995" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:35

Use `scale_y_continuous` from the `ggplot2` package with `breaks = seq(1, 16)` in order to include all 16 seeds.

scale_y_continuous

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=1235" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:55

Use `geom_text` from the `ggplot2` package with `label = percent(pct)` to apply the percentage to each tile in the heatmap.

geom_text | scales

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=1255" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:40

Use `scale_x_discrete` and `scale_y_continuous` both with `expand = c(0, 0)` to remove the space between the x and y axis and the heatmap tiles. David calls this flattening.

scale_x_discrete | scale_y_continuous

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=1300" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:15

Use `scale_y_reverse` to flip the order of the y-axis from 1-16 to 16-1.

scale_y_reverse

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=1935" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:45

Use `cor` from the `stats` package to calculate the `correlation` between `seed` and `tourney_finish`. Then plotted to determine if there is a correlation over time.

cor | geom_line

stats | ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=2085" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:50

Use `geom_smooth` with `method = "loess"` to add a smoothing line with confidence bound to aid in seeing the trend between `seed` and `reg_percent`.

geom_smooth

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=2390" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:10

Use `fct_lump` from the `forcats` package to lump together all the conference except for the `n` most frequent.

fct_lump

forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=2530" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:55

Use `geom_jitter` from the `ggplot2` package instead of `geom_boxplot` to avoid overplotting which makes it easier to visualize the points that make up the distribution of the `seed` variable.

geom_jitter

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=2575" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:05

Use `geom_smooth` with `method = "lm"` to aid in seeing the trend between `reg_percent` and `tourney_w`.

geom_smooth

ggplot2



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=2825" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:54:20

Create a `dot pipe function` using `.` and `%>%` to avoid duplicating summary statistics with `summarize`.

. | %>%

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=3260" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:35

Use `glue` from the `glue` package to concatenate together `school` and `n_entries` on the `geo_col` y-axis.

glue

glue



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=3395" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:59:50

Summary of screencast.

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/-RD8GNCNsCk?start=3590" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

