---
title: |
  Nobel Prize Winners
description: |
  Data manipulation, Graphing for EDA (Exploratory Data Analysis)
date: 2019-05-24
date-format: long
aliases:
  - "Nobel Prize Winners.html"
---

Notable topics: Data manipulation, Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2019-05-24

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/nobel-prize.Rmd)

## Screencast

<div id="yt-player" data-video-id="yWSpLfmES7w"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-120">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(120, this)">0:2:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_col</span><span class="badge-functions badge bg-info">%/%</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a stacked bar plot using geom_col and the aes function's fill argument (also bins years into decades with truncated division operator %/%)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-210">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(210, this)">0:3:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">n_distinct</span></div><div></div></div>
    <div class="topic_description">
      <p>Using n_distinct function to quickly count unique years in a group</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-540">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(540, this)">0:9:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">distinct</span></div><div></div></div>
    <div class="topic_description">
      <p>Using distinct function and its .keep_all argument to de-duplicate data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-650">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(650, this)">0:10:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">coalesce</span></div><div></div></div>
    <div class="topic_description">
      <p>Using coalesce function to replace NAs in a variable (similar to SQL COALESCE verb)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-970">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(970, this)">0:16:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">year</span></div><div><span class="badge-packages badge bg-primary">lubridate</span></div></div>
    <div class="topic_description">
      <p>Using year function from lubridate package to calculate (approx.) age of laureates at time of award</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1010">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1010, this)">0:16:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_reorder function to arrange boxplot graph by the median age of winners</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1370">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1370, this)">0:22:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">count</span></div><div></div></div>
    <div class="topic_description">
      <p>Defining a new variable within the count function (like doing a mutate in the count function)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1420">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1420, this)">0:23:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_col</span><span class="badge-functions badge bg-info">facet_wrap</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a small multiples bar plot using geom_col and facet_wrap functions</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1575">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1575, this)">0:26:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">WDIsearch</span></div><div><span class="badge-packages badge bg-primary">WDI</span></div></div>
    <div class="topic_description">
      <p>Importing income data from WDI package to explore relationship between high/low income countries and winners</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2025">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2025, this)">0:33:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_relevel</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_relevel to change the levels of a categorical income variable (e.g., &quot;Upper middle income&quot;) so that the ordering makes sense</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2185">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2185, this)">0:36:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting to explore new dataset of nobel laureate publications</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2665">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2665, this)">0:44:25</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">mean</span></div><div></div></div>
    <div class="topic_description">
      <p>Taking the mean of a subset of data without needing to fully filter the data beforehand</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2955">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2955, this)">0:49:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">rank</span></div><div></div></div>
    <div class="topic_description">
      <p>Using rank function and its ties.method argument to add the ordinal number of a laureate's publication (e.g., 1st paper, 2nd paper)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3910">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3910, this)">1:05:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_histogram</span></div><div></div></div>
    <div class="topic_description">
      <p>Lots of playing around with exploratory histograms (geom_histogram)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4005">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4005, this)">1:06:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Discussion of right-censoring as an issue (people winning the Nobel prize but still having active careers)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4220">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4220, this)">1:10:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
