---
title: "Nobel Prize Winners"
description: "Data manipulation, Graphing for EDA (Exploratory Data Analysis)"
date: 2019-05-24
date-format: long
---

Notable topics: Data manipulation, Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2019-05-24

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/nobel-prize.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:00

Creating a stacked bar plot using geom_col and the aes function's fill argument (also bins years into decades with truncated division operator %/%)

geom_col | %/%

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=120" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:3:30

Using n_distinct function to quickly count unique years in a group

n_distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=210" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:00

Using distinct function and its .keep_all argument to de-duplicate data

distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=540" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:50

Using coalesce function to replace NAs in a variable (similar to SQL COALESCE verb)

coalesce

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=650" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:10

Using year function from lubridate package to calculate (approx.) age of laureates at time of award

year

lubridate



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:50

Using fct_reorder function to arrange boxplot graph by the median age of winners

fct_reorder

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=1010" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:50

Defining a new variable within the count function (like doing a mutate in the count function)

count

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=1370" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:40

Creating a small multiples bar plot using geom_col and facet_wrap functions

geom_col | facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=1420" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:15

Importing income data from WDI package to explore relationship between high/low income countries and winners

WDIsearch

WDI



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=1575" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:45

Using fct_relevel to change the levels of a categorical income variable (e.g., "Upper middle income") so that the ordering makes sense

fct_relevel

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=2025" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:36:25

Starting to explore new dataset of nobel laureate publications

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=2185" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:25

Taking the mean of a subset of data without needing to fully filter the data beforehand

mean

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=2665" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:15

Using rank function and its ties.method argument to add the ordinal number of a laureate's publication (e.g., 1st paper, 2nd paper)

rank

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=2955" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:05:10

Lots of playing around with exploratory histograms (geom_histogram)

geom_histogram

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=3910" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:06:45

Discussion of right-censoring as an issue (people winning the Nobel prize but still having active careers)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=4005" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:10:20

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/yWSpLfmES7w?start=4220" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

