---
title: "NYC Squirrel Census"
description: "Map visualization (ggmap package)"
date: 2019-11-01
date-format: long
---

Notable topics: Map visualization (ggmap package)

Recorded on: 2019-11-01

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/nyc-squirrels.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:5:45

Starter EDA of latitude and longitude using geom_point

geom_point

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=345" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:6:45

Aggregating squirrel counts by hectare to get a "binned" map

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=405" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:00

Investigating colour notes

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=540" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:30

Asking question, "Are there areas of the parks where we see certain-coloured squirrels

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:45

Plotting latitude and percentage of gray squirrels to answer, "Do we get a lower proportion of gray squirrels as we go farther north?"

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=765" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:30

Using logistic regression to test gray squirrel (proportion as we go farther north)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=810" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:30

Noting that he could have used original data sets as input for logistic regression function

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=990" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:30

"Does a squirrel run away?" based on location in the park (latitude), using logistic regression

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:45

Using summarise_at function to apply same function to multiple variables

summarise_at

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1245" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:25

Loading ggmap package

NA

ggmap



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1525" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:00

Start using ggmap, with the get_map function

get_map

ggmap



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1620" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:20

Decision to not set up Google API key to use ggmap properly

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1700" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:15

Using the sf package to read in a shapefile of Central Park

NA

sf



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1815" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:40

Using read_sf function from sf package to import a shapefile into R

read_sf

sf



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1840" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:30

Using geom_sf function from sf package to visualise the imported shapefile

geom_sf

sf



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:45

Combining shapefile "background" with relevant squirrel data in one plot

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=1965" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:40

Visualising pathways (footpaths, bicycle paths) in the shapefile

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2080" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:55

Finishing visualisation and moving on to analysing activity types

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2275" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:38:45

Selecting fields based on whether they end with "ing", then gathering those fields into tidy format

ends_with | gather

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2325" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:50

Decision to create a Shiny visualisation

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2390" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:30

Setting Shiny app settings (e.g., slider for minimum number of squirrels)

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2490" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:15

Setting up Shiny app options / variables

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2535" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:43:50

Explanation of why setting up options in Shiny app the way he did

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:00

Solving error "Discrete value supplied to continuous scale"

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2760" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:50

First draft of Shiny app

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2810" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:35

Creating a dynamic midpoint for the two-gradient scale in the app

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=2915" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:30

Adding additional variables of more behaviours to Shiny app (kuks, moans, runs from, etc.)

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=3090" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:10

"What are the distributions of some of these [behaviours]?"

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=3190" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:50

Adding ground location (above ground, ground plane) to Shiny app

NA

shiny



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=3410" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:20

Summary of screencast

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/6GV9sAD6Pi0?start=3500" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

