---
title: "Plants in Danger"
description: "Data manipulation, Web scraping (rvest package) and SelectorGadget"
date: 2020-08-18
date-format: long
---

Notable topics: Data manipulation, Web scraping (rvest package) and SelectorGadget

Recorded on: 2020-08-18

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/2020_08_18_extinct_plants.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:00

Using `count`, `fct_lump`, and `fct_reorder` to get an overview of categorical data

count | fct_lump | fct_reorder

dplyr | forcats



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=120" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:5:00

Using `fct_relevel` to reorder the "Before 1900" level to the first location leaving the other levels in their existing order

fct_relevel

forcats



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=300" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:05

Using `n` and `sum` in `fct_reorder` to reorder factor levels when there are multiple categories in `count`

fct_reorder

forcats



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=485" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:00

Using `reorder_within` and `scale_y_reordered` such that the values are ordered within each facet

reorder_within | scale_y_reordered

tidytext



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=720" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:55

Using `axis.text.x" to rotate overlapping labels

axis.text.x

ggplot2



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=895" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:05

Using `filter` and `fct_lump` to lump all levels except for the 8 most frequest facet panels

filter | fct_lump

dplyr | forcats



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=1145" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:55

Using `separate` to separate the character column `binomial_name` into multiple columns (genus and species)

separate

tidyr



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=1615" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:20

Using `fct_lump` within `count` to lump all levels except for the 8 most frequent genus

fct_lump

forcats



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=1700" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:30

Using `rvest` and `SelectorGadget` to web scrape list of species

read_html | html_nodes | html_text

rvest



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=2730" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:35

Using `str_trim` to remove whitespace from character string

str_trim

stringr



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=2975" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:50:00

Using `separate` to separate character string into genus, species, and rest/citation columns and using `extra = "merge"` to merge extra pieces into the rest/citation column

separate

tidyr



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=3000" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:00

Using `rvest` and `SelectorGadget` to web scrape image links

read_html | html_nodes | html_text 
html_attr | inner_join | paste0 | map

rvest | dplyr
purrr



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=3060" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:50

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/f7Rc1bvMgZY?start=3470" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

