---
title: "Ramen Reviews"
description: "Web scraping (rvest package)"
date: 2019-06-04
date-format: long
---

Notable topics: Web scraping (rvest package)

Recorded on: 2019-06-04

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/ramen-ratings.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:1:45

Looking at the website the data came from

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=105" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:2:55

Using gather function (now pivot_longer) to convert wide data to long (tidy) format

gather

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:4:15

Graphing counts of all categorical variables at once, then exploring them

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=255" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:5:35

Using fct_lump function to lump three categorical variables to the top N categories and "Other"

fct_lump

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=335" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:45

Using reorder_within function to re-order factors that have the same name across multiple facets

reorder_within

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=465" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:10

Using lm function (linear model) to predict star rating

lm

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=550" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:50

Visualising effects (and 95% CI) of indendent variables in linear model with a coefficient plot (TIE fighter plot)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=590" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:30

Using fct_relevel function to get "Other" as the base reference level for categorical independent variables in a linear model

fct_relevel

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=690" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:05

Using extract function and regex to split a camelCase variable into two separate variables

extract

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=785" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:45

Using facet_wrap function to split coefficient / TIE fighter plot into three separate plots, based on type of coefficient

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=885" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:40

Using geom_vline function to add reference line to graph

geom_vline

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=940" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:20

Using unnest_tokens function from tidytext package to explore the relationship between variety (a sparse categorical variable) and star rating

unnest_tokens

tidytext



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1040" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:55

Explanation of how he would approach variety variable with Lasso regression

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1135" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:35

Web scraping the using rvest package and SelectorGadget (Chrome Extension CSS selector)

NA

rvest



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:20

Actually writing code for web scraping, using read_html, html_node, and html_table functions

read_html | html_node | html_table

rvest



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1280" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:25

Using clean_names function from janitor package to clean up names of variables

clean_names

janitor



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1345" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:05

Explanation of web scraping task: get full review text using the links from the review summary table scraped above

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1385" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:40

Using parse_number function as alternative to as.integer function to cleverly drop extra weird text in review number

parse_number

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1540" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:45

Using SelectorGadget (Chrome Extension CSS selector) to identify part of page that contains review text

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1605" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:35

Using html_nodes, html_text, and str_subset functions to write custom function to scrape review text identified in step above

html_nodes | html_text | str_subset

rvest



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1655" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:15

Adding message function to custom scraping function to display URLs as they are being scraped

message

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1755" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:15

Using unnest_tokens and anti_join functions to split review text into individual words and remove stop words (e.g., "the", "or", "and")

unnest_tokens | anti_join

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1815" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:05

Catching a mistake in the custom function causing it to read the same URL every time

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1865" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:55

Using str_detect function to filter out review paragraphs without a keyword in it

str_detect

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1915" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:40

Using str_remove function and regex to get rid of string that follows a specific pattern

str_remove

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=1960" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:10

Explanation of possibly and safely functions in purrr package

possibly | safely

purrr



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=2050" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:45

Reviewing output of the URL that failed to scrape, including using character(0) as a default null value

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=2265" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:00

Using pairwise_cor function from widyr package to see which words tend to appear in reviews together

pairwise_cor

widyr



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=2880" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:05

Using igraph and ggraph packages to make network plot of word correlations

NA

igraph | ggraph



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3065" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:55

Using geom_node_text function to add labels to network plot

geom_node_text

igraph | ggraph



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3115" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:52:35

Including all words (not just those connected to others) as vertices in the network plot

NA

igraph | ggraph



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3155" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:54:40

Tweaking and refining network plot aesthetics (vertex size and colour)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3280" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:00

Weird hack for getting a dark outline on hard-to-see vertex points

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3360" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:59:15

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/tCa2di7aEP4?start=3555" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

