---
title: "Seattle Pet Names"
description: "Hypergeometric hypothesis testing, Adjusting for multiple hypothesis testing"
date: 2019-03-16
date-format: long
---

Notable topics: Hypergeometric hypothesis testing, Adjusting for multiple hypothesis testing

Recorded on: 2019-03-16

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/seattle-pets.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:40

Using mdy function from lubridate package to convert character-formatted date to date-class

mdy

lubridate



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=160" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:4:20

Exploratory bar graph showing top species of cats, using geom_col function

geom_col

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=260" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:6:30

Specifying facet_wrap function's ncol argument to get graphs stacked vertically (instead of side-by-side)

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=390" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:9:55

Asking, "Are some animal names associated with particular dog breeds?"

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=595" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:15

Explanation of add_count function

add_count

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=675" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:35

Adding up various metrics (e.g., number of names overall, number of breeds overall), but note a mistake that gets fixed at 17:05

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=755" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:10

Calculating a ratio for names that appear over-represented within a breed, then explaining how small samples can be misleading

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:05

Spotting and fixing an aggregation mistake

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1025" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:55

Explanation of how to investigate which names might be over-represented within a breed

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1075" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:55

Explanation of how to use hypergeometric distribution to test for name over-representation

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1135" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:40

Using phyper function to calculate p-values for a one-sided hypergeometric test

phyper

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1240" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:30

Additional explanation of hypergeometric distribution

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1410" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:24:00

First investigation of why and how to interpret a p-value histogram (second at 29:45, third at 37:45, and answer at 39:30)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1440" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:15

Noticing that we are missing zeros (i.e., having a breed/name combination with 0 dogs), which is important for the hypergeometric test

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1515" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:10

Using complete function to turn implicit zeros (for breed/name combination) into explicit zeros

complete

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:45

Second investigation of p-value histogram (after adding in implicit zeros)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1785" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:55

Explanation of multiple hypothesis testing and correction methods (e.g., Bonferroni, Holm), and applying using p.adjust function

p.adjust

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=1915" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:25

Explanation of False Discovery Rate (FDR) control as a method for correcting for multiple hypothesis testing, and applying using p.adjust function

p.adjust

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2065" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:45

Third investigation of p-value histogram, to hunt for under-represented names

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2265" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:30

Answer to why the p-value distribution is not well-behaved

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2370" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:40

Using crossing function to created a simulated dataset to explore how different values affect the p-value

crossing

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2560" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:55

Explanation of how total number of names and total number of breeds affects p-value

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2695" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:00

More general explanation of what different shapes of p-value histogram might indicate

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2760" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:30

Renaming variables within a transmute function, using backticks to get names with spaces in them

transmute

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:20

Using kable function from the knitr package to create a nice-looking table

kable

knitr



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=2960" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:50:00

Explanation of one-side p-value (as opposed to two-sided p-value)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=3000" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:55

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/EF4A4OtQprg?start=3235" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

