---
title: |
  Space Launches
description: |
  Graphing for EDA (Exploratory Data Analysis)
date: 2019-01-15
date-format: long
aliases:
  - "Space Launches.html"
---

Notable topics: Graphing for EDA (Exploratory Data Analysis)

Recorded on: 2019-01-15

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/space-launches.Rmd)

## Screencast

<div id="yt-player" data-video-id="ZyPrP_Yo1BA"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-280">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(280, this)">0:4:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_detect</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_detect function to find missions with &quot;Apollo&quot; in their name</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-380">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(380, this)">0:6:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting EDA (exploratory data analysis)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-910">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(910, this)">0:15:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_collapse</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_collapse function to recode factors (similar to case_when function)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1005">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1005, this)">0:16:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">countrycode</span></div><div><span class="badge-packages badge bg-primary">countrycode</span></div></div>
    <div class="topic_description">
      <p>Using countrycode function from countrycode package to get full country names from country codes (e.g. &quot;RU&quot; becomes &quot;Russia&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1095">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1095, this)">0:18:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using replace_na function to convert NA (missing) observations to &quot;Other&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1150">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1150, this)">0:19:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_line</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a line graph using geom_line function with different colours for different categories</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1265">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1265, this)">0:21:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_reorder function to reorder factors in line graph above, in order to make legend more readable</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1920">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1920, this)">0:32:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_col</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a bar graph, using geom_col function, of most active (by number of launches) private or startup agencies</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2105">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2105, this)">0:35:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">%/%</span></div><div></div></div>
    <div class="topic_description">
      <p>Using truncated division operator %/% to bin data into decades</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2135">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2135, this)">0:35:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">complete</span></div><div></div></div>
    <div class="topic_description">
      <p>Using complete function to turn implicit zeros into explicit zeros (makes for a cleaner line graph)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2235">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2235, this)">0:37:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">facet_wrap</span></div><div></div></div>
    <div class="topic_description">
      <p>Using facet_wrap function to create small multiples of a line graph, then proceeding to tweak the graph</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2570">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2570, this)">0:42:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">semi_join</span></div><div></div></div>
    <div class="topic_description">
      <p>Using semi_join function as a filtering step</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2595">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2595, this)">0:43:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_point</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_point to create a timeline of launches by vehicle type</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2840">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2840, this)">0:47:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of why boxplots over time might not be a good visualization choice</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2880">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2880, this)">0:48:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_jitter</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_jitter function to tweak the timeline graph to be more readable</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3090">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3090, this)">0:51:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Creating a second timeline graph for US vehicles and launches</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3395">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3395, this)">0:56:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
