---
title: |
  Student-Teacher Ratios
description: |
  WDI package (World Development Indicators)
date: 2019-05-09
date-format: long
aliases:
  - "Student-Teacher Ratios.html"
---

Notable topics: WDI package (World Development Indicators)

Recorded on: 2019-05-09

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/student-teacher-ratios.Rmd)

## Screencast

<div id="yt-player" data-video-id="NoUHdrailxA"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-450">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(450, this)">0:7:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">slice</span></div><div></div></div>
    <div class="topic_description">
      <p>Using slice function to select 10 highest and 10 lowest student-teacher ratios (like a filter using row numbers)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-755">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(755, this)">0:12:35</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">WDI</span></div></div>
    <div class="topic_description">
      <p>Adding GDP per capita to a dataset using WDI package</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1060">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1060, this)">0:17:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_text to add labels to points on a scatterplot</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1140">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1140, this)">0:19:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">WDIsearch</span></div><div><span class="badge-packages badge bg-primary">WDI</span></div></div>
    <div class="topic_description">
      <p>Using WDIsearch function from WDI package to search for country population data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1400">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1400, this)">0:23:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of trick with geom_text function's check_overlap argument to get label for US to appear by rearranging row order</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1545">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1545, this)">0:25:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">comma_format</span></div><div><span class="badge-packages badge bg-primary">scales</span></div></div>
    <div class="topic_description">
      <p>Using comma_format function from scales format to get more readable numeric legend (e.g., &quot;500,000,000&quot; instead of &quot;5e+08&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1675">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1675, this)">0:27:55</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">WDI</span></div></div>
    <div class="topic_description">
      <p>Exploring different education-related indicators in the WDI package</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1915">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1915, this)">0:31:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">spread</span><span class="badge-functions badge bg-info">pivot_wider</span></div><div></div></div>
    <div class="topic_description">
      <p>Using spread function (now pivot_wider) to turn data from tidy to wide format</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1935">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1935, this)">0:32:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">to_snake_case</span></div><div><span class="badge-packages badge bg-primary">snakecase</span></div></div>
    <div class="topic_description">
      <p>Using to_snake_case function from snakecase package to conver field names to snake_case</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2910">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2910, this)">0:48:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring female/male school secondary school enrollment</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3110">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3110, this)">0:51:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Note of caution on keeping confounders in mind when interpreting scatterplots</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3150">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3150, this)">0:52:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">lm</span></div><div></div></div>
    <div class="topic_description">
      <p>Creating a linear regression of secondary school enrollment to explore confounders</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3270">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3270, this)">0:54:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Discussing the actual confounder (GDP per capita) in the linear regression above</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3440">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3440, this)">0:57:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding world region as another potential confounder</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3480">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3480, this)">0:58:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">aov</span></div><div></div></div>
    <div class="topic_description">
      <p>Using aov function (ANOVA) to explore confounders further</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4010">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4010, this)">1:06:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Reviewing and interpreting the final linear regression model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4080">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4080, this)">1:08:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">cor</span></div><div></div></div>
    <div class="topic_description">
      <p>Using cor function (correlation) to get correlation matrix for three variables (and brief explanation of multi-collinearity)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4210">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4210, this)">1:10:10</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
