---
title: "Tennis Tournaments"
description: "NA"
date: 2019-04-09
date-format: long
---

Notable topics: NA

Recorded on: 2019-04-09

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/grand-slams.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:5:00

Identifying duplicated rows ands fixing them

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=300" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:15

Using add_count and fct_reorder functions to order categories that are broken down into sub-categories for graphing

add_count | fct_reorder

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=675" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:00

Tidying graph titles (e.g., replacing underscores with spaces) using str_to_title and str_replace functions

str_to_title | str_replace

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=780" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:00

Using inner_join function to merge datasets

inner_join

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=900" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:30

Calculating age from date of birth using difftime and as.numeric functions

difftime | as.numeric

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=930" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:35

Adding simple calculations like mean and median into the text portion of markdown document

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=995" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:45

Looking at distribution of wins by sex using overlapping histograms

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1065" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:55

Binning years into decades using truncated division %/%

%/%

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1135" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:15

Splitting up boxplots so that they are separated into pairs (M/F) across a different group (decade) using interaction function

interaction

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1215" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:30

Analyzing distribution of ages across decades, looking specifically at the effect of Serena Williams (one individual having a disproportionate affect on the data, making it look like there's a trend)

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1230" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:24:30

Avoiding double-counting of individuals by counting their average age instead of their age at each win

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1470" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:20

Starting analysis to predict winner of Grand Slam tournaments

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=1820" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:35:00

Creating rolling count using row_number function to make a count of previous tournament experience

row_number

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2100" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:45

Creating rolling win count using cumsum function

cumsum

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2385" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:00

Lagging rolling win count using lag function (otherwise we get information about a win before a player has actually won, for prediction purposes)

lag

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2460" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:43:30

Asking, "When someone is a finalist, what is their probability of winning as a function of previous tournaments won?"

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2610" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:00

Asking, "How does the number of wins a finalist has affect their chance of winning?"

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2880" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:00

Backtesting simple classifier where person with more tournament wins is predicted to win the given tournament

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=2940" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:45

Creating classifier that gives points based on how far a player got in previous tournaments

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=3105" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:52:55

Using match function to turn name of round reached (1st round, 2nd round, …) into a number score (1, 2, …)

match

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=3175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:54:20

Using cummean function to get score of average past performance (instead of cumsum function)

cummean

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=3260" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:04:10

Pulling names of rounds (1st round, 2nd round, … ) based on the rounded numeric score of previous performance

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/YWUCUfEeNJI?start=3850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

