---
title: "Thanksgiving Dinner"
description: "Survey data, Network graphing"
date: 2018-11-21
date-format: long
---

Notable topics: Survey data, Network graphing

Recorded on: 2018-11-21

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/thanksgiving.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:4:10

Exploratory bar chart of age distribution (and gender) of survey respondents

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=250" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:40

Using count function on multiple columns to get detailed counts

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=460" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:25

Parsing numbers from text using parse_number function, then using those numbers to re-level an ordinal factor (income bands)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=685" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:05

Exploring relationship between income and using homemade (vs. canned) cranberry sauce

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=785" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:00

Adding group = 1 argument to the aes function to properly display a line chart

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=840" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:30

Rotating text for axis labels that overlap

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=870" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:50

Getting confidence intervals for proportions using Jeffreys interval (using beta distribution with an uniformative prior)

qbeta

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1010" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:55

Explanation of Clopper-Pearson approach as alternative to Jeffreys interval

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1075" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:30

Using geom_ribbon function add shaded region to line chart that shows confidence intervals

geom_ribbon

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1110" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:55

Using starts_with function to select fields with names that start with a certain string (e.g., using "pie" selects "pie1" and "pie2")

starts_with

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1315" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:55

Using gather function to get wide-format data to tidy (tall) format

gather

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1375" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:45

Using str_remove and regex to remove digits from field values (e.g., "dessert1" and "dessert2" get turned into "dessert")

str_remove

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1425" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:00

"What are people eating?" Graphing pies, sides, and desserts

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1620" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:00

Using fct_reorder function to reorder foods based on how popular they are

fct_reorder

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1680" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:45

Using n_distinct function count the number of unique respondents

n_distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1725" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:25

Using facet_wrap function to facet food types into their own graphs

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1825" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:50

Using parse_number function to convert age ranges as character string into a numeric field

parse_number

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=1970" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:35:35

Exploring relationship between US region and food types

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2135" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:36:15

Using group_by, then mutate, then count to calculate a complicated summary

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:35

Exploring relationship between praying at Thanksgiving (yes/no) and food types

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2435" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:30

Empirical Bayes binomial estimation for calculating binomial confidence intervals (see Dave's book on Empirical Bayes)

add_ebb_estimate

ebbr



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2550" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:30

Asking, "What sides/desserts/pies are eaten together?"

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2730" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:20

Calculating pairwise correlation of food types

pairwise_cor

widyr



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2780" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:49:05

Network graph of pairwise correlation

NA

ggraph | igraph



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=2945" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:40

Adding text labels to nodes using geom_node_text function

geom_node_text

ggraph | igraph



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3100" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:00

Getting rid of unnecessary graph elements (e.g., axes, gridlines) with theme_void function

theme_void

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3180" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:53:25

Explanation of network graph relationships

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3205" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:55:05

Adding dimension to network graph (node colour) to represent the type of food

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3305" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:45

Fixing overlapping text labels using the geom_node_text function's repel argument

geom_node_text

ggraph | igraph



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3465" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:55

Tweaking display of percentage legend to be in more readable format (e.g., "40%" instead of "0.4")

NA

scales



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3535" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:05

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/rxJZT0duwfU?start=3605" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

