---
title: |
  Thanksgiving Dinner
description: |
  Survey data, Network graphing
date: 2018-11-21
date-format: long
aliases:
  - "Thanksgiving Dinner.html"
---

Notable topics: Survey data, Network graphing

Recorded on: 2018-11-21

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/thanksgiving.Rmd)

## Screencast

<div id="yt-player" data-video-id="rxJZT0duwfU"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-250">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(250, this)">0:4:10</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploratory bar chart of age distribution (and gender) of survey respondents</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-460">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(460, this)">0:7:40</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using count function on multiple columns to get detailed counts</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-685">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(685, this)">0:11:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Parsing numbers from text using parse_number function, then using those numbers to re-level an ordinal factor (income bands)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-785">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(785, this)">0:13:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring relationship between income and using homemade (vs. canned) cranberry sauce</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-840">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(840, this)">0:14:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding group = 1 argument to the aes function to properly display a line chart</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-870">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(870, this)">0:14:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Rotating text for axis labels that overlap</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1010">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1010, this)">0:16:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">qbeta</span></div><div></div></div>
    <div class="topic_description">
      <p>Getting confidence intervals for proportions using Jeffreys interval (using beta distribution with an uniformative prior)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1075">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1075, this)">0:17:55</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of Clopper-Pearson approach as alternative to Jeffreys interval</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1110">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1110, this)">0:18:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_ribbon</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_ribbon function add shaded region to line chart that shows confidence intervals</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1315">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1315, this)">0:21:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">starts_with</span></div><div></div></div>
    <div class="topic_description">
      <p>Using starts_with function to select fields with names that start with a certain string (e.g., using &quot;pie&quot; selects &quot;pie1&quot; and &quot;pie2&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1375">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1375, this)">0:22:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">gather</span></div><div></div></div>
    <div class="topic_description">
      <p>Using gather function to get wide-format data to tidy (tall) format</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1425">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1425, this)">0:23:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_remove</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_remove and regex to remove digits from field values (e.g., &quot;dessert1&quot; and &quot;dessert2&quot; get turned into &quot;dessert&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1620">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1620, this)">0:27:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>&quot;What are people eating?&quot; Graphing pies, sides, and desserts</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1680">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1680, this)">0:28:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_reorder</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_reorder function to reorder foods based on how popular they are</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1725">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1725, this)">0:28:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">n_distinct</span></div><div></div></div>
    <div class="topic_description">
      <p>Using n_distinct function count the number of unique respondents</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1825">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1825, this)">0:30:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using facet_wrap function to facet food types into their own graphs</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1970">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1970, this)">0:32:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">parse_number</span></div><div></div></div>
    <div class="topic_description">
      <p>Using parse_number function to convert age ranges as character string into a numeric field</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2135">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2135, this)">0:35:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring relationship between US region and food types</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2175">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2175, this)">0:36:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using group_by, then mutate, then count to calculate a complicated summary</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2435">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2435, this)">0:40:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring relationship between praying at Thanksgiving (yes/no) and food types</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2550">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2550, this)">0:42:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">add_ebb_estimate</span></div><div><span class="badge-packages badge bg-primary">ebbr</span></div></div>
    <div class="topic_description">
      <p>Empirical Bayes binomial estimation for calculating binomial confidence intervals (see Dave's book on Empirical Bayes)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2730">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2730, this)">0:45:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;What sides/desserts/pies are eaten together?&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2780">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2780, this)">0:46:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pairwise_cor</span></div><div><span class="badge-packages badge bg-primary">widyr</span></div></div>
    <div class="topic_description">
      <p>Calculating pairwise correlation of food types</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2945">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2945, this)">0:49:05</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">ggraph</span><span class="badge-packages badge bg-primary">igraph</span></div></div>
    <div class="topic_description">
      <p>Network graph of pairwise correlation</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3100">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3100, this)">0:51:40</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_node_text</span></div><div><span class="badge-packages badge bg-primary">ggraph</span><span class="badge-packages badge bg-primary">igraph</span></div></div>
    <div class="topic_description">
      <p>Adding text labels to nodes using geom_node_text function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3180">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3180, this)">0:53:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">theme_void</span></div><div></div></div>
    <div class="topic_description">
      <p>Getting rid of unnecessary graph elements (e.g., axes, gridlines) with theme_void function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3205">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3205, this)">0:53:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of network graph relationships</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3305">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3305, this)">0:55:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding dimension to network graph (node colour) to represent the type of food</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3465">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3465, this)">0:57:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_node_text</span></div><div><span class="badge-packages badge bg-primary">ggraph</span><span class="badge-packages badge bg-primary">igraph</span></div></div>
    <div class="topic_description">
      <p>Fixing overlapping text labels using the geom_node_text function's repel argument</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3535">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3535, this)">0:58:55</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">scales</span></div></div>
    <div class="topic_description">
      <p>Tweaking display of percentage legend to be in more readable format (e.g., &quot;40%&quot; instead of &quot;0.4&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3605">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3605, this)">1:00:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
