---
title: "TidyTuesday Tweets"
description: "Text mining (tidytext package)"
date: 2019-01-07
date-format: long
---

Notable topics: Text mining (tidytext package)

Recorded on: 2019-01-07

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/tidytuesday-tweets.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:1:20

Importing an rds file using read_rds function

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=80" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:2:55

Using floor_date function from lubridate package to round dates down (that's what the floor part does) to the month level

floor_date

lubridate



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=175" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:5:25

Asking, "Which tweets get the most re-tweets?"

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=325" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:5:50

Using contains function to select only columns that contain a certain string ("retweet" in this case)

contains

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=350" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:05

Exploring likes/re-tweets ratio, including dealing with one or the other being 0 (which would cause divide by zero error)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=485" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:00

Starting exploration of actual text of tweets

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=660" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:35

Using unnest_tokens function from tidytext package to break tweets into individual words (using token argument specifically for tweet-style text)

unnest_tokens

tidytext



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=695" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:12:55

Using anti_join function to filter out stop words (e.g., "and", "or", "the") from tokenized data frame

anti_join

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=775" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:45

Calculating summary statistics per word (average retweets and likes), then looking at distributions

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=885" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:16:00

Explanation of Poisson log normal distribution (number of retweets fits this distribution)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=960" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:17:45

Additional example of Poisson log normal distribution (number of likes)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=1065" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:20

Explanation of geometric mean as better summary statistic than median or arithmetic mean

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=1100" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:25:20

Using floor_date function from lubridate package to floor dates to the week level and tweaking so that a week starts on Monday (default is Sunday)

floor_date

lubridate



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=1520" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:20

Asking, "What topic is each week about?" using just the tweet text

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=1820" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:30

Calculating TF-IDF of tweets, with week as the "document"

bind_tf_idf

tidytext



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=1890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:45

Using top_n and group_by functions to select the top tf-idf score for each week

top_n

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2025" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:55

Using str_detect function to filter out "words" that are just numbers (e.g., 16, 36)

str_detect

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2275" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:00

Using distinct function with .keep_all argument to ensure only top 1 result, as alternative to top_n function (which includes ties)

distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2460" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:30

Making Jenny Bryan disappointed

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2550" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:55

Using geom_text function to add text labels to graph to show to word associated with each week

geom_text

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2575" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:44:10

Using geom_text_repel function from ggrepel package as an alternative to geom_text function for adding text labels to graph

geom_text_repel

ggrepel



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2650" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:30

Using rvest package to scrape web data from a table in Tidy Tuesday README

NA

rvest



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=2790" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:00

Starting to look at #rstats tweets

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=3060" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:35

Spotting signs of fake accounts with purchased followers (lots of hashtags)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=3395" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:59:15

Explanation of spotting fake accounts

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=3555" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:45

Using str_detect to filter out web URLs

str_detect

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=3645" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:03:55

Using str_count function and some regex to count how many hashtags a tweet has

str_count

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=3835" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:07:25

Creating a Bland-Altman plot (total on x-axis, variable of interest on y-axis)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=4045" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:08:45

Using geom_text function with check_overlap argument to add labels to scatterplot

geom_text

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=4125" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:12:20

Asking, "Who are the most active #rstats tweeters?"

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=4340" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:15:00

Summary of screncast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/KE9ItC3doEU?start=4500" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

