---
title: |
  TidyTuesday Tweets
description: |
  Text mining (tidytext package)
date: 2019-01-06
date-format: long
aliases:
  - "TidyTuesday Tweets.html"
---

Notable topics: Text mining (tidytext package)

Recorded on: 2019-01-06

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/tidytuesday-tweets.Rmd)

## Screencast

<div id="yt-player" data-video-id="KE9ItC3doEU"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-80">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(80, this)">0:1:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Importing an rds file using read_rds function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-175">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(175, this)">0:2:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">floor_date</span></div><div><span class="badge-packages badge bg-primary">lubridate</span></div></div>
    <div class="topic_description">
      <p>Using floor_date function from lubridate package to round dates down (that's what the floor part does) to the month level</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-325">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(325, this)">0:5:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;Which tweets get the most re-tweets?&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-350">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(350, this)">0:5:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">contains</span></div><div></div></div>
    <div class="topic_description">
      <p>Using contains function to select only columns that contain a certain string (&quot;retweet&quot; in this case)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-485">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(485, this)">0:8:05</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Exploring likes/re-tweets ratio, including dealing with one or the other being 0 (which would cause divide by zero error)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-660">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(660, this)">0:11:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting exploration of actual text of tweets</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-695">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(695, this)">0:11:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">unnest_tokens</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Using unnest_tokens function from tidytext package to break tweets into individual words (using token argument specifically for tweet-style text)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-775">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(775, this)">0:12:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">anti_join</span></div><div></div></div>
    <div class="topic_description">
      <p>Using anti_join function to filter out stop words (e.g., &quot;and&quot;, &quot;or&quot;, &quot;the&quot;) from tokenized data frame</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-885">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(885, this)">0:14:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Calculating summary statistics per word (average retweets and likes), then looking at distributions</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-960">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(960, this)">0:16:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of Poisson log normal distribution (number of retweets fits this distribution)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1065">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1065, this)">0:17:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Additional example of Poisson log normal distribution (number of likes)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1100">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1100, this)">0:18:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of geometric mean as better summary statistic than median or arithmetic mean</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1520">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1520, this)">0:25:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">floor_date</span></div><div><span class="badge-packages badge bg-primary">lubridate</span></div></div>
    <div class="topic_description">
      <p>Using floor_date function from lubridate package to floor dates to the week level and tweaking so that a week starts on Monday (default is Sunday)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1820">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1820, this)">0:30:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;What topic is each week about?&quot; using just the tweet text</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1890">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1890, this)">0:31:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">bind_tf_idf</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Calculating TF-IDF of tweets, with week as the &quot;document&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2025">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2025, this)">0:33:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">top_n</span></div><div></div></div>
    <div class="topic_description">
      <p>Using top_n and group_by functions to select the top tf-idf score for each week</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2275">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2275, this)">0:37:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_detect</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_detect function to filter out &quot;words&quot; that are just numbers (e.g., 16, 36)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2460">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2460, this)">0:41:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">distinct</span></div><div></div></div>
    <div class="topic_description">
      <p>Using distinct function with .keep_all argument to ensure only top 1 result, as alternative to top_n function (which includes ties)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2550">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2550, this)">0:42:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Making Jenny Bryan disappointed</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2575">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2575, this)">0:42:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_text function to add text labels to graph to show to word associated with each week</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2650">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2650, this)">0:44:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text_repel</span></div><div><span class="badge-packages badge bg-primary">ggrepel</span></div></div>
    <div class="topic_description">
      <p>Using geom_text_repel function from ggrepel package as an alternative to geom_text function for adding text labels to graph</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2790">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2790, this)">0:46:30</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">rvest</span></div></div>
    <div class="topic_description">
      <p>Using rvest package to scrape web data from a table in Tidy Tuesday README</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3060">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3060, this)">0:51:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting to look at #rstats tweets</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3395">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3395, this)">0:56:35</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Spotting signs of fake accounts with purchased followers (lots of hashtags)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3555">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3555, this)">0:59:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explanation of spotting fake accounts</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3645">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3645, this)">1:00:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_detect</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_detect to filter out web URLs</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3835">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3835, this)">1:03:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_count</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_count function and some regex to count how many hashtags a tweet has</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4045">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4045, this)">1:07:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Creating a Bland-Altman plot (total on x-axis, variable of interest on y-axis)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4125">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4125, this)">1:08:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">geom_text</span></div><div></div></div>
    <div class="topic_description">
      <p>Using geom_text function with check_overlap argument to add labels to scatterplot</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4340">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4340, this)">1:12:20</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;Who are the most active #rstats tweeters?&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4500">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4500, this)">1:15:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screncast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
