---
title: "TV Golden Age"
description: "Data manipulation, Logistic regression"
date: 2019-01-09
date-format: long
---

Notable topics: Data manipulation, Logistic regression

Recorded on: 2019-01-09

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/golden-age-tv.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:25

Quick tip on how to start exploring a new dataset

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=145" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:30

Investigating inconsistency of shows having a count of seasons that is different from the number of seasons given in the data

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=450" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:10

Using %in% operator and all function to only get shows that have a first season and don't have skipped seasons in the data

%in% | all

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=610" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:30

Asking, "Which seasons have the most variation in ratings?"

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=930" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:25

Using facet_wrap function to separate different shows on a line graph into multiple small graphs

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=1225" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:20:50

Writing custom embedded function to get width of breaks on the x-axis to always be even (e.g., season 2, 4, 6, etc.)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=1250" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:50

Committing, finding, and explaining a common error of using the same variable name when summarizing multiple things

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=1430" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:20

Using truncated division operator %/% to bin data into two-year bins instead of annual (e.g., 1990 and 1991 get binned to 1990)

%/%

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=1700" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:31:30

Using subsetting (with square brackets) within the mutate function to calculate mean on only a subset of data (without needing to filter)

mutate

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=1890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:50

Using gather function (now pivot_longer) to get metrics as columns into tidy format, in order to graph them all at once with a facet_wrap

gather

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2030" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:36:30

Using pmin function to lump all seasons after 4 into one row (it still shows "4", but it represents "4+")

pmin

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2190" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:00

Asking, "If season 1 is good, do you get a second season?" (show survival)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2340" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:35

Using paste0 and spread functions to get season 1-3 ratings into three columns, one for each season

paste0 | spread

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2435" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:05

Using distinct function with .keep_all argument remove duplicates by only keeping the first one that appears

distinct

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2525" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:50

Using logistic regression to answer, "Does season 1 rating affect the probability of getting a second season?" (note he forgets to specify the family argument, fixed at 57:25)

glm

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2750" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:35

Using ntile function to divide data into N bins (5 in this case), then eventually using cut function instead

ntile | cut

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=2915" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:00

Adding year as an independent variable to the logistic regression model

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3420" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:58:50

Adding an interaction term (season 1 interacting with year) to the logistic regression model

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3530" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:59:55

Using augment function as a method of visualizing and interpreting coefficients of regression model

augment

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3595" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:30

Using crossing function to create new data to test the logistic regression model on and interpret model coefficients

crossing

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:03:40

Fitting natural splines using the splines package, which would capture a non-linear relationship

NA

splines



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3820" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:06:15

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/oYGi2wgSJaM?start=3975" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

