---
title: |
  TV Golden Age
description: |
  Data manipulation, Logistic regression
date: 2019-01-08
date-format: long
aliases:
  - "TV Golden Age.html"
---

Notable topics: Data manipulation, Logistic regression

Recorded on: 2019-01-08

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/golden-age-tv.Rmd)

## Screencast

<div id="yt-player" data-video-id="oYGi2wgSJaM"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-145">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(145, this)">0:2:25</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Quick tip on how to start exploring a new dataset</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-450">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(450, this)">0:7:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Investigating inconsistency of shows having a count of seasons that is different from the number of seasons given in the data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-610">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(610, this)">0:10:10</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">%in%</span><span class="badge-functions badge bg-info">all</span></div><div></div></div>
    <div class="topic_description">
      <p>Using %in% operator and all function to only get shows that have a first season and don't have skipped seasons in the data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-930">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(930, this)">0:15:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;Which seasons have the most variation in ratings?&quot;</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1225">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1225, this)">0:20:25</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">facet_wrap</span></div><div></div></div>
    <div class="topic_description">
      <p>Using facet_wrap function to separate different shows on a line graph into multiple small graphs</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1250">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1250, this)">0:20:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Writing custom embedded function to get width of breaks on the x-axis to always be even (e.g., season 2, 4, 6, etc.)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1430">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1430, this)">0:23:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Committing, finding, and explaining a common error of using the same variable name when summarizing multiple things</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1700">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1700, this)">0:28:20</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">%/%</span></div><div></div></div>
    <div class="topic_description">
      <p>Using truncated division operator %/% to bin data into two-year bins instead of annual (e.g., 1990 and 1991 get binned to 1990)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1890">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1890, this)">0:31:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">mutate</span></div><div></div></div>
    <div class="topic_description">
      <p>Using subsetting (with square brackets) within the mutate function to calculate mean on only a subset of data (without needing to filter)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2030">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2030, this)">0:33:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">gather</span></div><div></div></div>
    <div class="topic_description">
      <p>Using gather function (now pivot_longer) to get metrics as columns into tidy format, in order to graph them all at once with a facet_wrap</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2190">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2190, this)">0:36:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pmin</span></div><div></div></div>
    <div class="topic_description">
      <p>Using pmin function to lump all seasons after 4 into one row (it still shows &quot;4&quot;, but it represents &quot;4+&quot;)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2340">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2340, this)">0:39:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Asking, &quot;If season 1 is good, do you get a second season?&quot; (show survival)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2435">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2435, this)">0:40:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">paste0</span><span class="badge-functions badge bg-info">spread</span></div><div></div></div>
    <div class="topic_description">
      <p>Using paste0 and spread functions to get season 1-3 ratings into three columns, one for each season</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2525">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2525, this)">0:42:05</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">distinct</span></div><div></div></div>
    <div class="topic_description">
      <p>Using distinct function with .keep_all argument remove duplicates by only keeping the first one that appears</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2750">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2750, this)">0:45:50</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">glm</span></div><div></div></div>
    <div class="topic_description">
      <p>Using logistic regression to answer, &quot;Does season 1 rating affect the probability of getting a second season?&quot; (note he forgets to specify the family argument, fixed at 57:25)</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2915">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2915, this)">0:48:35</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">ntile</span><span class="badge-functions badge bg-info">cut</span></div><div></div></div>
    <div class="topic_description">
      <p>Using ntile function to divide data into N bins (5 in this case), then eventually using cut function instead</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3420">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3420, this)">0:57:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding year as an independent variable to the logistic regression model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3530">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3530, this)">0:58:50</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding an interaction term (season 1 interacting with year) to the logistic regression model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3595">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3595, this)">0:59:55</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">augment</span></div><div></div></div>
    <div class="topic_description">
      <p>Using augment function as a method of visualizing and interpreting coefficients of regression model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3630">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3630, this)">1:00:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">crossing</span></div><div></div></div>
    <div class="topic_description">
      <p>Using crossing function to create new data to test the logistic regression model on and interpret model coefficients</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3820">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3820, this)">1:03:40</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">splines</span></div></div>
    <div class="topic_description">
      <p>Fitting natural splines using the splines package, which would capture a non-linear relationship</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3975">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3975, this)">1:06:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Summary of screencast</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
