---
title: "US Dairy Consumption"
description: "Time series analysis, Forecasting (sweep package)"
date: 2019-01-29
date-format: long
---

Notable topics: Time series analysis, Forecasting (sweep package)

Recorded on: 2019-01-29

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/us-dairy.Rmd)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:2:50

Identifying the need for a gather step

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=170" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:4:40

Changing snake case to title case using str_to_title and str_replace_all functions

str_to_title | str_replace_all

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=280" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:6:20

Identifying need for separating categories into major and minor categories (e.g., "Cheese Other" can be divided into "Cheese" and "Other")

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=380" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:10

Using separate function to split categories into major and minor categories (good explanation of "extra" argument, which merges additional separations into one field)

separate

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=430" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:8:20

Using coalesce function to deal with NAs resulting from above step

coalesce

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=500" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:10:30

Dealing with graph of minor category that is linked to multiple major categories ("Other" linked to "Cheese" and "Frozen")

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=630" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:10

Introducing fct_lump function as an approach to work with many categories

fct_lump

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=790" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:50

Introducing facetting (facet_wrap function) as second alternative to working with many categories

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=890" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:15:50

Dealing with "Other" category having two parts to it by using ifelse function in the cleaning step (e.g., go from "Other" to "Other Cheese")

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=950" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:19:45

Looking at page for the sweep package

NA

sweep



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1185" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:21:20

Using tk_ts function to coerce a tibble to a timeseries

tk_ts

sweep



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1280" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:10

Turning year column (numeric) into a date by adding number of years to Jan 1, 0001

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1330" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:00

Nesting time series object into each combination of category and product

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1560" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:27:50

Applying ETS (Error, Trend, Seasonal) model to each time series

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1670" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:10

Using sw_glance function (sweep package's version of glance function) to pull out model parameters from model field created in above step

sw_glance

sweep



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1690" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:29:45

Using sw_augment function to append fitted values and residuals from the model to the original data

sw_augment

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1785" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:50

Visualising actual and fitted values on the same graph to get a look at the ETS model

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1850" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:32:10

Using Arima function (note the capital A) as alternative to ETS (not sure what difference is between arima and Arima)

Arima

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=1930" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:35:00

Forecasting into the future using an ETS model using various functions: unnest, sw_sweep, forecast

sw_sweep | forecast

sweep



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2100" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:37:45

Using geom_ribbon function to add confidence bounds to forecast

geom_ribbon

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2265" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:20

Forecasting using auto-ARIMA (instead of ETS)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2420" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:40:55

Applying two forecasting methods at the same time (auto-ARIMA and ETS) using the crossing function

crossing

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2455" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:55

Quick test of how invoke function works (used to call a function easily, e.g., when it is a character string instead of called directly)

invoke

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2515" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:35

Removing only one part of legend (line type of solid or dashed) using scale_linetype_discrete function

scale_linetype_discrete

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=2855" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:51:25

Using gather function to clean up new dataset

gather

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=3085" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:52:05

Using fct_recode to fix a typo in a categorical variable

fct_recode

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=3125" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:56:00

Copy-pasting previous forecasting code to cheese and reviewing any changes needed

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=3360" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:20

Discussing alternative approach: creating interactive visualisation using shiny package to do direct comparisons

NA

shiny



<iframe class="video" src="https://www.youtube.com/embed/13iG_HkEPVc?start=3440" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

