---
title: "US Incarceration"
description: "Animated map (gganimate package), Dealing with missing data"
date: 2019-01-25
date-format: long
---

Notable topics: Animated map (gganimate package), Dealing with missing data

Recorded on: 2019-01-25

Timestamps by: Alex Cookson

[View code](NA)

## Full screencast
<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:4:30

Creating a facetted (small multiples) line graph of incarceration rate by urbanicity and race over time

facet_wrap

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=270" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:7:45

Discussion of statistical testing of incarceration rates by urbanicity (e.g., rural, suburban)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=465" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:11:25

Exploring the extent of missing data on prison population

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=685" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:14:15

Using any function to filter down to states that have at least one (hence the any function) row of non-missing data

any

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=855" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:40

Using cut function to manually bin data along user-specified intervals

cut

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=1120" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:24:15

Starting to create a choropleth map of incarceration rate by state

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=1455" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:26:20

Using match function to match two-letter state abbreviation to full state name, in order to get data needed to create a map

match

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=1580" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:28:00

Actually typing the code (now that we have the necessary data) to create a choropleth map

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=1680" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:05

Using str_remove function and regex to chop off the end of county names (e.g., "Allen Parish" becomes "Allen")

str_remove

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=1985" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:33:30

Making choropleth more specific by drilling down to county-level data

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=2010" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:41:10

Starting to make an animated choropleth map using gganimate

NA

gganimate



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=2470" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:42:20

Using modulo operator %% to choose every 5th year

%%

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=2540" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:43:45

Using scale_fill_gradient2 function's limits argument to exclude unusally high values that were blowing out the scale

scale_fill_gradient2

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=2625" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:48:15

Using summarise_at function to apply the same function to multiple fields at the same time

summarise_at

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=2895" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:50:10

Starting to investigate missing data (how much is missing, where is it missing, etc.)

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=3010" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:54:50

Creating a line graph that excludes counties with missing data

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=3290" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:57:05

Summary of screencast

NA

NA



<iframe class="video" src="https://www.youtube.com/embed/78kv808ZU6o?start=3425" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

