---
title: |
  Wine Ratings
description: |
  Text mining (tidytext package), LASSO regression (glmnet package)
date: 2019-05-30
date-format: long
aliases:
  - "Wine Ratings.html"
---

Notable topics: Text mining (tidytext package), LASSO regression (glmnet package)

Recorded on: 2019-05-30

Timestamps by: Alex Cookson

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/wine-ratings.Rmd)

## Screencast

<div id="yt-player" data-video-id="AQzZNIyjyWM"></div>

## Timestamps

```{=html}
<div id="topics">
  <div class="topic">
    <h3 id="ts-195">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(195, this)">0:3:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">extract</span></div><div><span class="badge-packages badge bg-primary">tidyr</span></div></div>
    <div class="topic_description">
      <p>Using extract function from tidyr package to pull out year from text field</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-555">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(555, this)">0:9:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">extract</span></div><div><span class="badge-packages badge bg-primary">tidyr</span></div></div>
    <div class="topic_description">
      <p>Changing extract function to pull out year column more accurately</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-780">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(780, this)">0:13:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Starting to explore prediction of points</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1020">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1020, this)">0:17:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">fct_lump</span><span class="badge-functions badge bg-info">fct_relevel</span></div><div></div></div>
    <div class="topic_description">
      <p>Using fct_lump on country variable to collapse countries into an &quot;Other&quot; category, then fct_relevel to set the baseline category for a linear model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1290">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1290, this)">0:21:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Investigating year as a potential confounding variable</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1485">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1485, this)">0:24:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Investigating &quot;taster_name&quot; as a potential confounding variable</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1665">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1665, this)">0:27:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">tidy</span></div><div><span class="badge-packages badge bg-primary">broom</span></div></div>
    <div class="topic_description">
      <p>Coefficient (TIE fighter) plot to see effect size of terms in a linear model, using tidy function from broom package</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1845">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1845, this)">0:30:45</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_replace</span></div><div></div></div>
    <div class="topic_description">
      <p>Polishing category names for presentation in graph using str_replace function</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-1935">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(1935, this)">0:32:15</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">augment</span></div><div></div></div>
    <div class="topic_description">
      <p>Using augment function to add predictions of linear model to original data</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2010">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2010, this)">0:33:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Plotting predicted points vs. actual points</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2085">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2085, this)">0:34:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using ANOVA to determine the amount of variation that explained by different terms</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2205">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2205, this)">0:36:45</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Using tidytext package to set up wine review text for Lasso regression</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2400">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2400, this)">0:40:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">pairwise_cor</span></div><div><span class="badge-packages badge bg-primary">widyr</span></div></div>
    <div class="topic_description">
      <p>Setting up and using pairwise_cor function to look at words that appear in reviews together</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2700">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2700, this)">0:45:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">cast_sparse</span></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Creating sparse matrix using cast_sparse function from tidytext package; used to perform a regression on positive/negative words</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2805">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2805, this)">0:46:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Checking if rownames of sparse matrix correspond to the wine_id values they represent</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2820">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2820, this)">0:47:00</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">glmnet</span></div></div>
    <div class="topic_description">
      <p>Setting up sparse matrix for using glmnet package to do sparse regression using Lasso method</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2895">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2895, this)">0:48:15</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">glmnet</span></div></div>
    <div class="topic_description">
      <p>Actually writing code for doing Lasso regression</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-2985">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(2985, this)">0:49:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Basic explanation of Lasso regression</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3060">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3060, this)">0:51:00</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">tidy</span></div><div></div></div>
    <div class="topic_description">
      <p>Putting Lasso model into tidy format</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3195">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3195, this)">0:53:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Explaining how the number of terms increases as lambda (penalty parameter) decreases</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3240">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3240, this)">0:54:00</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Answering how we choose a lambda value (penalty parameter) for Lasso regression</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3405">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3405, this)">0:56:45</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Using parallelization for intensive computations</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3510">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3510, this)">0:58:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Adding price (from original linear model) to Lasso regression</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3735">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3735, this)">1:02:15</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">glmnet</span></div></div>
    <div class="topic_description">
      <p>Shows glmnet.fit piece of a Lasso (glmnet) model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-3810">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(3810, this)">1:03:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Picking a lambda value (penalty parameter) and explaining which one to pick</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4095">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4095, this)">1:08:15</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Taking most extreme coefficients (positive and negative) by grouping theme by direction</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4230">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4230, this)">1:10:30</button>
    </h3>
    <div class="topic_badges"><div></div><div><span class="badge-packages badge bg-primary">tidytext</span></div></div>
    <div class="topic_description">
      <p>Demonstrating tidytext package's sentiment lexicon, then looking at individual reviews to demonstrate the model</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4650">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4650, this)">1:17:30</button>
    </h3>
    <div class="topic_badges"><div></div><div></div></div>
    <div class="topic_description">
      <p>Visualizing each coefficient's effect on a single review</p>

    </div>
  </div>
  <div class="topic">
    <h3 id="ts-4830">
      <button class="btn btn-link btn-timestamp" onClick="playerSkipToTimestamp(4830, this)">1:20:30</button>
    </h3>
    <div class="topic_badges"><div><span class="badge-functions badge bg-info">str_trunc</span></div><div></div></div>
    <div class="topic_description">
      <p>Using str_trunc to truncate character strings</p>

    </div>
  </div>
</div>
```
     
<script>
// 2. This code loads the IFrame Player API code asynchronously.
var tag = document.createElement("script");

tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName("script")[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

// 3. This function creates an <iframe> (and YouTube player)
//    after the API code downloads.
var videoId = document.getElementById("yt-player").dataset.videoId;
var player;
function onYouTubeIframeAPIReady() {
  player = new YT.Player("yt-player", {
    height: "486",
    width: "864",
    videoId: videoId,
    playerVars: {
      "playsinline": 1
    },
    events: {
      onStateChange: function(event) {
        if (event.data == YT.PlayerState.PLAYING) {
          followTimestamps()
        }
      }
    }
  });
}

function playerSkipToTimestamp(seconds, tsElement) {
  player.seekTo(seconds, true)
  tsElement.scrollIntoView()
  document.getElementById("screencast").scrollIntoView()
}

const timestamps = Array.from(document.querySelectorAll('.topic h3[id^="ts-"]'))
  .map(el => el.id.replace('ts-', ''))

function followTimestamps() {
  if (player.getPlayerState() !== 1) {
    return
  }
  const currentTime = `${Math.floor(player.getCurrentTime())}`
  if (timestamps.includes(currentTime)) {
    const el = document.getElementById(`ts-${currentTime}`)
    if (el) {
      el.scrollIntoView()
      document.getElementById("screencast").scrollIntoView()
    }
  }
  setTimeout(followTimestamps, 1000)
}
</script>
