---
title: "X-Men Comics"
description: "Data manipulation, Lollipop graph, Grouping using floor division"
date: 2020-06-30
date-format: long
---

Notable topics: Data manipulation, Lollipop graph, Grouping using floor division

Recorded on: 2020-06-30

Timestamps by: Eric Fletcher

[View code](https://github.com/dgrtwo/data-screencasts/blob/master/uncanny-xmen.Rmd)

## Full screencast
<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

## Timestamps

### 0:07:25

Using `separate` to separate the name from secrete identity in the `character` column

separate

tidyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=445" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:09:55

Using `summarize` and `across` to find the frequency of the action variables and find out how many issues each action was used for each character

summarize | across

dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=595" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:13:25

Create a `geom_col` chart to visualize which character speaks in the most issues

geom_col | fct_reorder

ggplot2 | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=805" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:18:35

Create a `geom_point` chart to visualize each character’s average lines per issue in which the character is depicted

geom_point | geom_text | geom_text_repel | 
summarize

ggplot2 | ggrepel | dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=1115" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:22:05

Create a `geom_point` chart to visualize each character’s average thoughts per issue in which the character is depicted

geom_point | geom_text | geom_text_repel | 
summarize

ggplot2 | ggrepel | dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=1325" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:23:10

Create a `geom_point` chart to visualize character’s speech versus thought ratio per issue in which the character is depicted

geom_point | geom_text | geom_text_repel | 
summarize

ggplot2 | ggrepel | dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=1390" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:30:05

Create a `geom_point` to visualize character’s number of lines while in costume versus not in costume

geom_point | pivot_longer | fct_reorder

ggplot2 | tidyr | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=1805" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:34:30

Create a `geom_point` chart to visualize the lines in costume versus lines out of costume ratio

geom_point | geom_text | geom_text_repel | 
summarize

ggplot2 | ggrepel | dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=2070" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:39:20

Create a `lollipop graph` using `geom_point` and `geom_errorbarh` to visualize the lines in costume versus lines out of costume ratio and their distance from 1.0 (1 to 1)

geom_point | fct_reorder | geom_errorbarh

ggplot2 | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=2360" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:45:00

Use `summarize` to find the frequency of each location and the total number of unique issues where the location is used

summarize | group_by | arrange

dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=2700" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:46:00

Use `summarize` and `fct_lump` to count how many issues each author has written while lumping together all authors except the most frequent

summarize | fct_lump

dplyr | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=2760" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:47:25

Use `summarize` and `fct_lump` to see if the authors rates of passing the Bechdel test differ from one another

summarize | fct_lump

dplyr | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=2845" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:52:45

Create a `geom_line` chart to visualize if the rates of passing the Bechdel test changed over time and `floor division` `%/%` to generate 20 observations per group

geom_line | summarize

dplyr



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=3165" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 0:54:35

Create a `geom_col` to visualize the amount of lines each character has per issue over time giving context to Bechdel test passing rates

geom_col | summarize | fct_lump | facet_wrap

ggplot | dplyr | forcats



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=3275" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

### 1:00:00

Summary of screencast

NA

NA



<iframe width="560" height="315" src="https://www.youtube.com/embed/NY0-IFet5AM?start=3600" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

